// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class alternativeCodes : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""alternativeCodes"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""ALTERNATIVE_CONTAINER_IDENTIFIER"",""doc"":""An alternative identification code of the equipment - usually provided from customer when container is customer owned."",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// An alternative identification code of the equipment - usually provided from customer when container is customer owned.
		/// </summary>
		private string _ALTERNATIVE_CONTAINER_IDENTIFIER;
		public virtual Schema Schema
		{
			get
			{
				return alternativeCodes._SCHEMA;
			}
		}
		/// <summary>
		/// An alternative identification code of the equipment - usually provided from customer when container is customer owned.
		/// </summary>
		public string ALTERNATIVE_CONTAINER_IDENTIFIER
		{
			get
			{
				return this._ALTERNATIVE_CONTAINER_IDENTIFIER;
			}
			set
			{
				this._ALTERNATIVE_CONTAINER_IDENTIFIER = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ALTERNATIVE_CONTAINER_IDENTIFIER;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ALTERNATIVE_CONTAINER_IDENTIFIER = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
