// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class brand : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"brand\",\"namespace\":\"com.maersk.orderhandling.containerma" +
				"in\",\"fields\":[{\"name\":\"brandCode\",\"doc\":\"The code of the Maersk brand.\",\"type\":\"" +
				"string\"},{\"name\":\"brandName\",\"doc\":\"The Maersk brand name.\",\"type\":\"string\"}]}");
		/// <summary>
		/// The code of the Maersk brand.
		/// </summary>
		private string _brandCode;
		/// <summary>
		/// The Maersk brand name.
		/// </summary>
		private string _brandName;
		public virtual Schema Schema
		{
			get
			{
				return brand._SCHEMA;
			}
		}
		/// <summary>
		/// The code of the Maersk brand.
		/// </summary>
		public string brandCode
		{
			get
			{
				return this._brandCode;
			}
			set
			{
				this._brandCode = value;
			}
		}
		/// <summary>
		/// The Maersk brand name.
		/// </summary>
		public string brandName
		{
			get
			{
				return this._brandName;
			}
			set
			{
				this._brandName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.brandCode;
			case 1: return this.brandName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.brandCode = (System.String)fieldValue; break;
			case 1: this.brandName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
