// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class cargoPackageType : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"cargoPackageType\",\"namespace\":\"com.maersk.orderhandling." +
				"containermain\",\"fields\":[{\"name\":\"cargoPackageTypeCode\",\"doc\":\"A standardised co" +
				"de for the packing style.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"car" +
				"goPackageTypeName\",\"doc\":\"A standardised cargo packaging style name.\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]},{\"name\":\"cargoPackageTypeDescription\",\"doc\":\"A te" +
				"xtual description of the cargo packaging style.\",\"default\":null,\"type\":[\"null\",\"" +
				"string\"]},{\"name\":\"alternativeCodes\",\"doc\":\"A list of alternative cargo package " +
				"type codes.\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"reco" +
				"rd\",\"name\":\"alternativeCode\",\"doc\":\"An alternative cargo package type code.\",\"na" +
				"mespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"alternative" +
				"Code\",\"doc\":\"Alternative code type code.\",\"type\":\"string\"},{\"name\":\"unPackageTyp" +
				"e\",\"doc\":\"The United Nations standardised code for a package type. If any altern" +
				"ative package type code exists - this should be always be specified.\",\"default\":" +
				"null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"unPackageType\",\"namespace\":\"com.mae" +
				"rsk.orderhandling.containermain\",\"fields\":[{\"name\":\"unPackageTypeCode\",\"doc\":\"Th" +
				"e United Nations standardized cargo package type code.\",\"type\":\"string\"},{\"name\"" +
				":\"unPackageTypeName\",\"doc\":\"The name of the United Nations standardized cargo pa" +
				"ckage type.\",\"type\":\"string\"},{\"name\":\"unPackageTypeDescription\",\"doc\":\"A descri" +
				"ption of the United Nations standardized cargo package type.\",\"default\":null,\"ty" +
				"pe\":[\"null\",\"string\"]}]}]},{\"name\":\"imDgPackageType\",\"doc\":\"Package types specif" +
				"ically described for hazardous cargo.\",\"default\":null,\"type\":[\"null\",{\"type\":\"re" +
				"cord\",\"name\":\"imDgPackageType\",\"namespace\":\"com.maersk.orderhandling.containerma" +
				"in\",\"fields\":[{\"name\":\"imDgPackageTypeCode\",\"doc\":\"The International Maritime Da" +
				"ngerous Goods code (Up to 5 characters). E.g.: 11HA2, 1A1.\",\"type\":\"string\"},{\"n" +
				"ame\":\"imDgPackageTypeName\",\"doc\":\"The packaging type name.\",\"type\":\"string\"},{\"n" +
				"ame\":\"imDgPackageTypeDescription\",\"doc\":\"A text describing the package type.\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]}]}]}]}}]}]}");
		/// <summary>
		/// A standardised code for the packing style.
		/// </summary>
		private string _cargoPackageTypeCode;
		/// <summary>
		/// A standardised cargo packaging style name.
		/// </summary>
		private string _cargoPackageTypeName;
		/// <summary>
		/// A textual description of the cargo packaging style.
		/// </summary>
		private string _cargoPackageTypeDescription;
		/// <summary>
		/// A list of alternative cargo package type codes.
		/// </summary>
		private IList<com.maersk.orderhandling.containermain.alternativeCode> _alternativeCodes;
		public virtual Schema Schema
		{
			get
			{
				return cargoPackageType._SCHEMA;
			}
		}
		/// <summary>
		/// A standardised code for the packing style.
		/// </summary>
		public string cargoPackageTypeCode
		{
			get
			{
				return this._cargoPackageTypeCode;
			}
			set
			{
				this._cargoPackageTypeCode = value;
			}
		}
		/// <summary>
		/// A standardised cargo packaging style name.
		/// </summary>
		public string cargoPackageTypeName
		{
			get
			{
				return this._cargoPackageTypeName;
			}
			set
			{
				this._cargoPackageTypeName = value;
			}
		}
		/// <summary>
		/// A textual description of the cargo packaging style.
		/// </summary>
		public string cargoPackageTypeDescription
		{
			get
			{
				return this._cargoPackageTypeDescription;
			}
			set
			{
				this._cargoPackageTypeDescription = value;
			}
		}
		/// <summary>
		/// A list of alternative cargo package type codes.
		/// </summary>
		public IList<com.maersk.orderhandling.containermain.alternativeCode> alternativeCodes
		{
			get
			{
				return this._alternativeCodes;
			}
			set
			{
				this._alternativeCodes = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.cargoPackageTypeCode;
			case 1: return this.cargoPackageTypeName;
			case 2: return this.cargoPackageTypeDescription;
			case 3: return this.alternativeCodes;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.cargoPackageTypeCode = (System.String)fieldValue; break;
			case 1: this.cargoPackageTypeName = (System.String)fieldValue; break;
			case 2: this.cargoPackageTypeDescription = (System.String)fieldValue; break;
			case 3: this.alternativeCodes = (IList<com.maersk.orderhandling.containermain.alternativeCode>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
