// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class commodityClassificationAssociation : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"commodityClassificationAssociation\",\"namespace\":\"com.mae" +
				"rsk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodityCode\",\"doc\":\"A cust" +
				"omer provided non-standardized commodity code.\",\"default\":null,\"type\":[\"null\",\"s" +
				"tring\"]},{\"name\":\"commodityName\",\"doc\":\"A customer provided non-standardized com" +
				"modity name.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"commodityClassif" +
				"ication\",\"doc\":\"Standardized commodity classification information.\",\"type\":{\"typ" +
				"e\":\"record\",\"name\":\"commodityClassification\",\"namespace\":\"com.maersk.orderhandli" +
				"ng.containermain\",\"fields\":[{\"name\":\"commodityGroup\",\"doc\":\"The commodity catego" +
				"ry type.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityGroup\"" +
				",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodi" +
				"tyGroupCode\",\"doc\":\"The identifying code for the commodity category.\",\"type\":\"st" +
				"ring\"},{\"name\":\"commodityGroupName\",\"doc\":\"The full name of the commodity catego" +
				"ry.\",\"type\":\"string\"}]}]},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the com" +
				"modity.\",\"type\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual description o" +
				"f the commodity.\",\"type\":\"string\"},{\"name\":\"commodityClassificationChild\",\"doc\":" +
				"\"A sub category commodity description. This is the top level of the recursion le" +
				"vel 0 not written out here to keep the Avro schema backward and forward compatib" +
				"le.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityClassificat" +
				"ionChild\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\"" +
				":\"commodityGroup\",\"doc\":\"The commodity category type.\",\"default\":null,\"type\":[\"n" +
				"ull\",\"commodityGroup\"]},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the commo" +
				"dity.\",\"type\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual description of " +
				"the commodity.\",\"type\":\"string\"},{\"name\":\"commodityClassificationChildL1\",\"doc\":" +
				"\"A sub category commodity description. The lower level of the recursion.\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityClassificationChildL1\"" +
				",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodi" +
				"tyGroup\",\"doc\":\"The commodity category type.\",\"default\":null,\"type\":[\"null\",\"com" +
				"modityGroup\"]},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the commodity.\",\"t" +
				"ype\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual description of the commo" +
				"dity.\",\"type\":\"string\"},{\"name\":\"commodityCodingSystem\",\"doc\":\"The system that d" +
				"efines the commodity codes: E.g.: Harmonized System, MARS Commodity codes, ...\"," +
				"\"type\":{\"type\":\"record\",\"name\":\"commodityCodingSystem\",\"namespace\":\"com.maersk.o" +
				"rderhandling.containermain\",\"fields\":[{\"name\":\"commodityCodingSystemCode\",\"doc\":" +
				"\"The uniquely identifying code for the commodity coding system.\",\"type\":\"string\"" +
				"},{\"name\":\"commodityCodingSystemName\",\"doc\":\"The full name of the commodity codi" +
				"ng system.\",\"type\":\"string\"}]}}]}]},{\"name\":\"commodityCodingSystem\",\"doc\":\"The s" +
				"ystem that defines the commodity codes: E.g.: Harmonized System, MARS Commodity " +
				"codes, ...\",\"type\":\"commodityCodingSystem\"}]}]},{\"name\":\"commodityCodingSystem\"," +
				"\"doc\":\"The system that defines the commodity codes: E.g.: Harmonized System, MAR" +
				"S Commodity codes, ...\",\"type\":\"commodityCodingSystem\"}]}}]}");
		/// <summary>
		/// A customer provided non-standardized commodity code.
		/// </summary>
		private string _commodityCode;
		/// <summary>
		/// A customer provided non-standardized commodity name.
		/// </summary>
		private string _commodityName;
		/// <summary>
		/// Standardized commodity classification information.
		/// </summary>
		private com.maersk.orderhandling.containermain.commodityClassification _commodityClassification;
		public virtual Schema Schema
		{
			get
			{
				return commodityClassificationAssociation._SCHEMA;
			}
		}
		/// <summary>
		/// A customer provided non-standardized commodity code.
		/// </summary>
		public string commodityCode
		{
			get
			{
				return this._commodityCode;
			}
			set
			{
				this._commodityCode = value;
			}
		}
		/// <summary>
		/// A customer provided non-standardized commodity name.
		/// </summary>
		public string commodityName
		{
			get
			{
				return this._commodityName;
			}
			set
			{
				this._commodityName = value;
			}
		}
		/// <summary>
		/// Standardized commodity classification information.
		/// </summary>
		public com.maersk.orderhandling.containermain.commodityClassification commodityClassification
		{
			get
			{
				return this._commodityClassification;
			}
			set
			{
				this._commodityClassification = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.commodityCode;
			case 1: return this.commodityName;
			case 2: return this.commodityClassification;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.commodityCode = (System.String)fieldValue; break;
			case 1: this.commodityName = (System.String)fieldValue; break;
			case 2: this.commodityClassification = (com.maersk.orderhandling.containermain.commodityClassification)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
