// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class commodityGroup : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""commodityGroup"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""commodityGroupCode"",""doc"":""The identifying code for the commodity category."",""type"":""string""},{""name"":""commodityGroupName"",""doc"":""The full name of the commodity category."",""type"":""string""}]}");
		/// <summary>
		/// The identifying code for the commodity category.
		/// </summary>
		private string _commodityGroupCode;
		/// <summary>
		/// The full name of the commodity category.
		/// </summary>
		private string _commodityGroupName;
		public virtual Schema Schema
		{
			get
			{
				return commodityGroup._SCHEMA;
			}
		}
		/// <summary>
		/// The identifying code for the commodity category.
		/// </summary>
		public string commodityGroupCode
		{
			get
			{
				return this._commodityGroupCode;
			}
			set
			{
				this._commodityGroupCode = value;
			}
		}
		/// <summary>
		/// The full name of the commodity category.
		/// </summary>
		public string commodityGroupName
		{
			get
			{
				return this._commodityGroupName;
			}
			set
			{
				this._commodityGroupName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.commodityGroupCode;
			case 1: return this.commodityGroupName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.commodityGroupCode = (System.String)fieldValue; break;
			case 1: this.commodityGroupName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
