// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class commodityCodingSystem : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""commodityCodingSystem"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""commodityCodingSystemCode"",""doc"":""The uniquely identifying code for the commodity coding system."",""type"":""string""},{""name"":""commodityCodingSystemName"",""doc"":""The full name of the commodity coding system."",""type"":""string""}]}");
		/// <summary>
		/// The uniquely identifying code for the commodity coding system.
		/// </summary>
		private string _commodityCodingSystemCode;
		/// <summary>
		/// The full name of the commodity coding system.
		/// </summary>
		private string _commodityCodingSystemName;
		public virtual Schema Schema
		{
			get
			{
				return commodityCodingSystem._SCHEMA;
			}
		}
		/// <summary>
		/// The uniquely identifying code for the commodity coding system.
		/// </summary>
		public string commodityCodingSystemCode
		{
			get
			{
				return this._commodityCodingSystemCode;
			}
			set
			{
				this._commodityCodingSystemCode = value;
			}
		}
		/// <summary>
		/// The full name of the commodity coding system.
		/// </summary>
		public string commodityCodingSystemName
		{
			get
			{
				return this._commodityCodingSystemName;
			}
			set
			{
				this._commodityCodingSystemName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.commodityCodingSystemCode;
			case 1: return this.commodityCodingSystemName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.commodityCodingSystemCode = (System.String)fieldValue; break;
			case 1: this.commodityCodingSystemName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
