// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Container event version 1.5
	/// </summary>
	public partial class ContainerMain : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ContainerMain\",\"doc\":\"Container event version 1.5\",\"name" +
				"space\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"shipmentNumbe" +
				"r\",\"doc\":\"The booking number for the shipment booking\",\"type\":\"string\"},{\"name\":" +
				"\"shipmentIdentifier\",\"doc\":\"INSTANCE_ID for the shipment. It is the primary key " +
				"for the SHIPMENT table in GCSS\",\"type\":\"string\"},{\"name\":\"shipmentVersionIdentif" +
				"ier\",\"doc\":\"INSTANCE_ID for the shipment version. It is the primary key for the " +
				"SHIPMENT_VERSION table in GCSS\",\"type\":\"string\"},{\"name\":\"shipmentVersionCreated" +
				"Datetime\",\"type\":\"string\",\"logicaltype\":\"timestamp-millis\"},{\"name\":\"shipmentVer" +
				"sionUpdatedDatetime\",\"type\":\"string\",\"logicaltype\":\"timestamp-millis\"},{\"name\":\"" +
				"shipmentStructureUpdateDatetime\",\"doc\":\"A timestamp for when any object in the s" +
				"hipment structure was latest updated.\",\"type\":\"string\",\"logicaltype\":\"timestamp-" +
				"millis\"},{\"name\":\"brand\",\"doc\":\"Identification of the carrier internal to Maersk" +
				". - The carrier owning the booking.\",\"type\":{\"type\":\"record\",\"name\":\"brand\",\"nam" +
				"espace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"brandCode\",\"" +
				"doc\":\"The code of the Maersk brand.\",\"type\":\"string\"},{\"name\":\"brandName\",\"doc\":" +
				"\"The Maersk brand name.\",\"type\":\"string\"}]}},{\"name\":\"partyAssociation\",\"doc\":\"I" +
				"nformation on carriers involved in the transport of the shipment.\",\"default\":nul" +
				"l,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"partyAssociation\",\"namespace\":\"com.mae" +
				"rsk.orderhandling.containermain\",\"fields\":[{\"name\":\"oceanCarrier\",\"doc\":\"Informa" +
				"tion on the company performing the transport at sea.\",\"default\":null,\"type\":[\"nu" +
				"ll\",{\"type\":\"record\",\"name\":\"oceanCarrier\",\"namespace\":\"com.maersk.orderhandling" +
				".containermain\",\"fields\":[{\"name\":\"partyRoleTypeName\",\"doc\":\"The type of party r" +
				"elating to the transport.\",\"type\":\"string\"},{\"name\":\"standardCarrierAlphaCode\",\"" +
				"doc\":\"The official operator code for the carrier/operator where the shipment is " +
				"booked\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]}]}]},{\"name\":\"totalBookedEqu" +
				"ipmentQuantity\",\"doc\":\"The total number of containers/equipment booked.\",\"defaul" +
				"t\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"totalBookedEquipmentFFE\",\"doc\":\"The tota" +
				"l number of containers/equipment booked equivalent to 40\' containers. E.g. If 3 " +
				"or 4 pieces of 20\' containers are booked this attribute is set to 2.\",\"default\":" +
				"null,\"type\":[\"null\",\"int\"]},{\"name\":\"totalBookedGrossWeight\",\"doc\":\"The total bo" +
				"oked weight of all cargo and equipment.\",\"default\":null,\"type\":[\"null\",\"double\"]" +
				"},{\"name\":\"totalBookedNetWeight\",\"doc\":\"The total booked weight of all cargo and" +
				" packaging but not including equipment weight.\",\"default\":null,\"type\":[\"null\",\"d" +
				"ouble\"]},{\"name\":\"totalBookedWeightWeightUnit\",\"doc\":\"The measurement unit of th" +
				"e total booked cargo weight.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"na" +
				"me\":\"totalBookedWeightWeightUnit\",\"namespace\":\"com.maersk.orderhandling.containe" +
				"rmain\",\"fields\":[{\"name\":\"unitOfMeasurementCode\",\"doc\":\"The measurement code - E" +
				".g.: KGS, Metric Ton, US LBS.\",\"type\":\"string\"},{\"name\":\"unitOfMeasurementName\"," +
				"\"doc\":\"The full name of the measurement unit.\",\"type\":\"string\"},{\"name\":\"measure" +
				"mentSystem\",\"doc\":\"Indicator for the measurement system used.\",\"type\":{\"type\":\"r" +
				"ecord\",\"name\":\"measurementSystem\",\"namespace\":\"com.maersk.orderhandling.containe" +
				"rmain\",\"fields\":[{\"name\":\"measurementSystemCode\",\"doc\":\"The abbreviated measure " +
				"system name. - E.g.: S.I. (Metric), Imperial, US Customary Units, Time, Industry" +
				" Standard.\",\"type\":\"string\"},{\"name\":\"measurementSystemName\",\"doc\":\"The full mea" +
				"sure system name.\",\"type\":\"string\"}]}}]}]},{\"name\":\"totalBookedVolume\",\"doc\":\"Th" +
				"e total booked volume of all cargo.\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"" +
				"name\":\"totalBookedVolumeVolumeUnit\",\"doc\":\"The measurement unit of the total boo" +
				"ked cargo volume.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"totalB" +
				"ookedVolumeVolumeUnit\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fie" +
				"lds\":[{\"name\":\"unitOfMeasurementCode\",\"doc\":\"The measurement code - E.g.: CBM, C" +
				"BF.\",\"type\":\"string\"},{\"name\":\"unitOfMeasurementName\",\"doc\":\"The full name of th" +
				"e measurement unit.\",\"type\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicat" +
				"or for the measurement system used.\",\"type\":\"measurementSystem\"}]}]},{\"name\":\"sh" +
				"ipmentEquipment\",\"doc\":\"A container/piece of equipment assigned to the booking.\"" +
				",\"type\":{\"type\":\"record\",\"name\":\"shipmentEquipment\",\"namespace\":\"com.maersk.orde" +
				"rhandling.containermain\",\"fields\":[{\"name\":\"shipmentEquipmentIdentifier\",\"doc\":\"" +
				"A unique identifier of the equipment assignment - (INSTANCE_ID in GCSS).\",\"type\"" +
				":\"string\"},{\"name\":\"container\",\"doc\":\"A description of the equipment assigned. -" +
				" Only available when equipment has been matched to booking.\",\"default\":null,\"typ" +
				"e\":[\"null\",{\"type\":\"record\",\"name\":\"container\",\"namespace\":\"com.maersk.orderhand" +
				"ling.containermain\",\"fields\":[{\"name\":\"isoCombinedCode\",\"doc\":\"The full ISO 6346" +
				" standardised container identification code.\",\"default\":null,\"type\":[\"null\",\"str" +
				"ing\"]},{\"name\":\"isoOwnerCode\",\"doc\":\"The owning company\'s ISO 6346 code.\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"isoCategoryCode\",\"doc\":\"The equipmen" +
				"t type ISO 6346 category code - this will be \'U\'.\",\"default\":null,\"type\":[\"null\"" +
				",\"string\"]},{\"name\":\"isoSerialNumber\",\"doc\":\"The ISO 6346 equipment identificati" +
				"on code serial number part.\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"isoC" +
				"heckDigitNumber\",\"doc\":\"The ISO 6346 equipment identification code check digit.\"" +
				",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"equipmentSizeType\",\"doc\":\"A clas" +
				"sification of size and type of the container.\",\"type\":{\"type\":\"record\",\"name\":\"e" +
				"quipmentSizeType\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":" +
				"[{\"name\":\"sizeTypeCode\",\"doc\":\"The ISO code for the size and type.\",\"default\":nu" +
				"ll,\"type\":[\"null\",\"string\"]},{\"name\":\"description\",\"doc\":\"A description of the c" +
				"ontainer size and type.\",\"type\":\"string\"},{\"name\":\"equipmentSize\",\"doc\":\"The Mae" +
				"rsk code for container length (size).\",\"type\":{\"type\":\"record\",\"name\":\"equipment" +
				"Size\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"eq" +
				"uipmentSizeCode\",\"doc\":\"The Maersk container length (size) code.\",\"type\":\"string" +
				"\"},{\"name\":\"equipmentSizeName\",\"doc\":\"The Maersk container length (size).\",\"type" +
				"\":\"string\"}]}},{\"name\":\"equipmentHeight\",\"doc\":\"The Maersk code for container he" +
				"ight.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"equipmentHeight\",\"" +
				"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"equipment" +
				"HeightCode\",\"doc\":\"The Maersk code for container height.\",\"type\":\"string\"},{\"nam" +
				"e\":\"equipmentHeightName\",\"doc\":\"The Maersk container height.\",\"type\":\"string\"}]}" +
				"]},{\"name\":\"equipmentType\",\"doc\":\"The Maersk description of type of equipment.\"," +
				"\"type\":{\"type\":\"record\",\"name\":\"equipmentType\",\"namespace\":\"com.maersk.orderhand" +
				"ling.containermain\",\"fields\":[{\"name\":\"equipmentTypeCode\",\"doc\":\"The Maersk code" +
				" for equipment type.\",\"type\":\"string\"},{\"name\":\"equipmentTypeName\",\"doc\":\"The Ma" +
				"ersk name for equipment type.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":" +
				"\"equipmentTypeChildEquipmentType\",\"doc\":\"Subtype description of the container ty" +
				"pe. This is upper level of the recursion level 0. It is not spelled out here to " +
				"allow the Avro schema to be backward and forward compliant.\",\"default\":null,\"typ" +
				"e\":[\"null\",{\"type\":\"record\",\"name\":\"equipmentTypeChildEquipmentType\",\"namespace\"" +
				":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"equipmentTypeCode\"," +
				"\"doc\":\"The Maersk code for equipment type.\",\"type\":\"string\"},{\"name\":\"equipmentT" +
				"ypeName\",\"doc\":\"The Maersk name for equipment type.\",\"default\":null,\"type\":[\"nul" +
				"l\",\"string\"]},{\"name\":\"equipmentTypeChildEquipmentTypeL1\",\"doc\":\"Subtype descrip" +
				"tion of the container type. This is lower level of the recursion level 1.\",\"defa" +
				"ult\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"equipmentTypeChildEquipmentTyp" +
				"eL1\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"equ" +
				"ipmentTypeCode\",\"doc\":\"The Maersk code for equipment type.\",\"type\":\"string\"},{\"n" +
				"ame\":\"equipmentTypeName\",\"doc\":\"The Maersk name for equipment type.\",\"default\":n" +
				"ull,\"type\":[\"null\",\"string\"]}]}]}]}]}]}}]}},{\"name\":\"alternativeCodes\",\"default\"" +
				":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"alternativeCodes\",\"namespace\":\"com" +
				".maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"ALTERNATIVE_CONTAINER_ID" +
				"ENTIFIER\",\"doc\":\"An alternative identification code of the equipment - usually p" +
				"rovided from customer when container is customer owned.\",\"default\":null,\"type\":[" +
				"\"null\",\"string\"]}]}]}]}]},{\"name\":\"equipmentProfile\",\"doc\":\"Specifies the type o" +
				"f reefer container to be used for the transport.\",\"default\":null,\"type\":[\"null\"," +
				"{\"type\":\"record\",\"name\":\"equipmentProfile\",\"namespace\":\"com.maersk.orderhandling" +
				".containermain\",\"fields\":[{\"name\":\"equipmentProfileCode\",\"doc\":\"The container ty" +
				"pe code.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"equipmentProfileName" +
				"\",\"doc\":\"The Maersk container type name.\",\"type\":\"string\"}]}]},{\"name\":\"cargoPac" +
				"kageType\",\"doc\":\"The style of packaging used in the container/equipment.\",\"defau" +
				"lt\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"cargoPackageType\",\"namespace\":\"" +
				"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"cargoPackageTypeCode\"" +
				",\"doc\":\"A standardised code for the packing style.\",\"default\":null,\"type\":[\"null" +
				"\",\"string\"]},{\"name\":\"cargoPackageTypeName\",\"doc\":\"A standardised cargo packagin" +
				"g style name.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cargoPackageTyp" +
				"eDescription\",\"doc\":\"A textual description of the cargo packaging style.\",\"defau" +
				"lt\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"alternativeCodes\",\"doc\":\"A list of a" +
				"lternative cargo package type codes.\",\"default\":null,\"type\":[\"null\",{\"type\":\"arr" +
				"ay\",\"items\":{\"type\":\"record\",\"name\":\"alternativeCode\",\"doc\":\"An alternative carg" +
				"o package type code.\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fiel" +
				"ds\":[{\"name\":\"alternativeCode\",\"doc\":\"Alternative code type code.\",\"type\":\"strin" +
				"g\"},{\"name\":\"unPackageType\",\"doc\":\"The United Nations standardised code for a pa" +
				"ckage type. If any alternative package type code exists - this should be always " +
				"be specified.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"unPackageT" +
				"ype\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"unP" +
				"ackageTypeCode\",\"doc\":\"The United Nations standardized cargo package type code.\"" +
				",\"type\":\"string\"},{\"name\":\"unPackageTypeName\",\"doc\":\"The name of the United Nati" +
				"ons standardized cargo package type.\",\"type\":\"string\"},{\"name\":\"unPackageTypeDes" +
				"cription\",\"doc\":\"A description of the United Nations standardized cargo package " +
				"type.\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"imDgPackageType\",\"d" +
				"oc\":\"Package types specifically described for hazardous cargo.\",\"default\":null,\"" +
				"type\":[\"null\",{\"type\":\"record\",\"name\":\"imDgPackageType\",\"namespace\":\"com.maersk." +
				"orderhandling.containermain\",\"fields\":[{\"name\":\"imDgPackageTypeCode\",\"doc\":\"The " +
				"International Maritime Dangerous Goods code (Up to 5 characters). E.g.: 11HA2, 1" +
				"A1.\",\"type\":\"string\"},{\"name\":\"imDgPackageTypeName\",\"doc\":\"The packaging type na" +
				"me.\",\"type\":\"string\"},{\"name\":\"imDgPackageTypeDescription\",\"doc\":\"A text describ" +
				"ing the package type.\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]}]}}]}]}]},{\"n" +
				"ame\":\"totalStuffedPackageQuantity\",\"doc\":\"Total number of outer level packages s" +
				"tuffed in the container/equipment.\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name" +
				"\":\"totalStuffedCustomerProductQuantity\",\"doc\":\"Total number of products stuffed " +
				"in the container/equipment.\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"tota" +
				"lStuffedGrossWeight\",\"doc\":\"The total weight of all cargo stuffed in the contain" +
				"er/equipment including outer level packaging.\",\"default\":null,\"type\":[\"null\",\"do" +
				"uble\"]},{\"name\":\"totalStuffedNetWeight\",\"doc\":\"The total net weight of all cargo" +
				" stuffed in the container excluding outer level packaging.\",\"default\":null,\"type" +
				"\":[\"null\",\"double\"]},{\"name\":\"totalStuffedWeightWeightUnit\",\"doc\":\"The measureme" +
				"nt unit of the total stuffed cargo weight in container/equipment.\",\"default\":nul" +
				"l,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"totalStuffedWeightWeightUnit\",\"namespa" +
				"ce\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"unitOfMeasuremen" +
				"tCode\",\"doc\":\"The measurement code - E.g.: KGS, Metric Ton, US LBS.\",\"type\":\"str" +
				"ing\"},{\"name\":\"unitOfMeasurementName\",\"doc\":\"The full name of the measurement un" +
				"it.\",\"type\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicator for the measu" +
				"rement system used.\",\"type\":\"measurementSystem\"}]}]},{\"name\":\"totalStuffedVolume" +
				"\",\"doc\":\"The total volume of cargo stuffed in the container/equipment.\",\"default" +
				"\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"totalStuffedVolumeVolumeUnit\",\"doc\":\"T" +
				"he measurement unit of the total stuffed cargo volume in the container/equipment" +
				".\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"totalStuffedVolumeVolu" +
				"meUnit\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"" +
				"unitOfMeasurementCode\",\"doc\":\"The measurement code - E.g.: CBM, CBF.\",\"type\":\"st" +
				"ring\"},{\"name\":\"unitOfMeasurementName\",\"doc\":\"The full name of the measurement u" +
				"nit.\",\"type\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicator for the meas" +
				"urement system used.\",\"type\":\"measurementSystem\"}]}]},{\"name\":\"isShipperOwned\",\"" +
				"doc\":\"Indicates if equipment is owned by the customer/shipper.\",\"type\":\"boolean\"" +
				"},{\"name\":\"isSubstituted\",\"doc\":\"Indicates if this equipment/container has been " +
				"replaced by another equipment/container of different size and/or type.\",\"type\":\"" +
				"boolean\"},{\"name\":\"isSubstitution\",\"doc\":\"Indicates of this equipment/container " +
				"has replaced another equipment/container but has different size and/or type prop" +
				"erties than the equipment/container originally assigned to the shipment.\",\"type\"" +
				":\"boolean\"},{\"name\":\"isReplaced\",\"doc\":\"Indicates if this equipment/container ha" +
				"s been replaced by another equipment/container of same size and type.\",\"type\":\"b" +
				"oolean\"},{\"name\":\"isReplacement\",\"doc\":\"Indicates of this equipment/container ha" +
				"s replaced another equipment/container of same size and type.\",\"type\":\"boolean\"}" +
				",{\"name\":\"shipmentEquipmentSubstituesOrReplaces\",\"doc\":\"The equipment/container " +
				"being substituted/replaced by the equipment/container that this event is about.\"" +
				",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"shipmentEquipmentSubstit" +
				"uesOrReplaces\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"" +
				"name\":\"shipmentEquipmentIdentifier\",\"doc\":\"A unique identifier of the equipment " +
				"that is substituted/replaced - (INSTANCE_ID in GCSS).\",\"type\":\"string\"}]}]},{\"na" +
				"me\":\"shipmentEquipmentCargoDistributions\",\"doc\":\"Description of cargo stuffing/d" +
				"istribution(s) in the container.\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\"," +
				"\"items\":{\"type\":\"record\",\"name\":\"shipmentEquipmentCargoDistribution\",\"doc\":\"A de" +
				"scription of a single cargo piece stuffing/distribution in the container.\",\"name" +
				"space\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"shipmentEquip" +
				"mentCargoDistributionIdentifier\",\"doc\":\"A unique identifier of the stuffing enti" +
				"ty. Taken from EQUIPMENT_STUFFING INSTANCE_ID in GCSS database.\",\"type\":\"string\"" +
				"},{\"name\":\"cargoPackageType\",\"doc\":\"The style of packaging used in the container" +
				"/equipment.\",\"default\":null,\"type\":[\"null\",\"cargoPackageType\"]},{\"name\":\"shipmen" +
				"tEquipmentCargoDistributionStatus\",\"doc\":\"Indicates whether the stuffing is plan" +
				"ned or actual.\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"enum\",\"name\":\"shipmentEqu" +
				"ipmentCargoDistributionStatus\",\"namespace\":\"com.maersk.orderhandling.containerma" +
				"in\",\"symbols\":[\"PLANNING\",\"ACTUAL\"]}}},{\"name\":\"stuffedPackageQuantity\",\"doc\":\"T" +
				"he number of outermost cargo packages in stuffing.\",\"default\":null,\"type\":[\"null" +
				"\",\"long\"]},{\"name\":\"stuffedCustomerProductQuantity\",\"doc\":\"The number of custome" +
				"r products in stuffing.\",\"default\":null,\"type\":[\"null\",\"long\"]},{\"name\":\"stuffed" +
				"GrossWeight\",\"doc\":\"The weight of cargo stuffed including outer packaging materi" +
				"als and palettes.\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"stuffedNetW" +
				"eight\",\"doc\":\"The weight of cargo stuffed excluding outer packaging materials an" +
				"d palettes.\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"stuffedWeightWeig" +
				"htUnit\",\"doc\":\"The measurement unit of the stuffed cargo gross weight.\",\"default" +
				"\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"weightWeightUnit\",\"namespace\":\"co" +
				"m.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"unitOfMeasurementCode\"," +
				"\"doc\":\"The measurement code - E.g.: KGS, Metric Ton, US LBS.\",\"type\":\"string\"},{" +
				"\"name\":\"unitOfMeasurementName\",\"doc\":\"The full name of the measurement unit.\",\"t" +
				"ype\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicator for the measurement " +
				"system used.\",\"type\":\"measurementSystem\"}]}]},{\"name\":\"stuffedVolume\",\"doc\":\"The" +
				" volume of cargo stuffed including packaging materials and palettes.\",\"default\":" +
				"null,\"type\":[\"null\",\"double\"]},{\"name\":\"stuffedVolumeVolumeUnit\",\"doc\":\"The meas" +
				"urement unit of the gross stuffed cargo volume.\",\"default\":null,\"type\":[\"null\",{" +
				"\"type\":\"record\",\"name\":\"stuffedVolumeVolumeUnit\",\"namespace\":\"com.maersk.orderha" +
				"ndling.containermain\",\"fields\":[{\"name\":\"unitOfMeasurementCode\",\"doc\":\"The measu" +
				"rement code - E.g.: Litre, Gallon, Cubic Metres.\",\"type\":\"string\"},{\"name\":\"unit" +
				"OfMeasurementName\",\"doc\":\"The full name of the measurement unit.\",\"type\":\"string" +
				"\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicator for the measurement system used." +
				"\",\"type\":\"measurementSystem\"}]}]},{\"name\":\"isOutOfGauge\",\"doc\":\"Indicate when th" +
				"e stuffed cargo is bigger than what can normally be stuffed in the given equipme" +
				"nt/container size.\",\"default\":false,\"type\":\"boolean\"},{\"name\":\"isStuffingConfirm" +
				"ed\",\"doc\":\"Flag indicating whether the physical stuffing of the cargo has comple" +
				"ted.\",\"default\":true,\"type\":\"boolean\"},{\"name\":\"shipmentLines\",\"doc\":\"The cargo(" +
				"s) stuffed in equipment/container and transported by the shipment.\",\"type\":{\"typ" +
				"e\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"shipmentLine\",\"doc\":\"One cargo item " +
				"stuffed in equipment/container and transported by the shipment.\",\"namespace\":\"co" +
				"m.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"shipmentLineIdentifier\"" +
				",\"doc\":\"Identification of the unique cargo that is stuffed in the container. The" +
				" CARGO INSTANCE_ID from GCSS database.\",\"type\":\"string\"},{\"name\":\"commodityClass" +
				"ificationAssociations\",\"doc\":\"A list classifying the cargo in commodity types pr" +
				"ovided by customer.\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"typ" +
				"e\":\"record\",\"name\":\"commodityClassificationAssociation\",\"namespace\":\"com.maersk." +
				"orderhandling.containermain\",\"fields\":[{\"name\":\"commodityCode\",\"doc\":\"A customer" +
				" provided non-standardized commodity code.\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"commodityName\",\"doc\":\"A customer provided non-standardized commodi" +
				"ty name.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"commodityClassificat" +
				"ion\",\"doc\":\"Standardized commodity classification information.\",\"type\":{\"type\":\"" +
				"record\",\"name\":\"commodityClassification\",\"namespace\":\"com.maersk.orderhandling.c" +
				"ontainermain\",\"fields\":[{\"name\":\"commodityGroup\",\"doc\":\"The commodity category t" +
				"ype.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityGroup\",\"na" +
				"mespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodityGr" +
				"oupCode\",\"doc\":\"The identifying code for the commodity category.\",\"type\":\"string" +
				"\"},{\"name\":\"commodityGroupName\",\"doc\":\"The full name of the commodity category.\"" +
				",\"type\":\"string\"}]}]},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the commodi" +
				"ty.\",\"type\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual description of th" +
				"e commodity.\",\"type\":\"string\"},{\"name\":\"commodityClassificationChild\",\"doc\":\"A s" +
				"ub category commodity description. This is the top level of the recursion level " +
				"0 not written out here to keep the Avro schema backward and forward compatible.\"" +
				",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityClassificationC" +
				"hild\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"co" +
				"mmodityGroup\",\"doc\":\"The commodity category type.\",\"default\":null,\"type\":[\"null\"" +
				",\"commodityGroup\"]},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the commodity" +
				".\",\"type\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual description of the " +
				"commodity.\",\"type\":\"string\"},{\"name\":\"commodityClassificationChildL1\",\"doc\":\"A s" +
				"ub category commodity description. The lower level of the recursion.\",\"default\":" +
				"null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityClassificationChildL1\",\"na" +
				"mespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodityGr" +
				"oup\",\"doc\":\"The commodity category type.\",\"default\":null,\"type\":[\"null\",\"commodi" +
				"tyGroup\"]},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the commodity.\",\"type\"" +
				":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual description of the commodity" +
				".\",\"type\":\"string\"},{\"name\":\"commodityCodingSystem\",\"doc\":\"The system that defin" +
				"es the commodity codes: E.g.: Harmonized System, MARS Commodity codes, ...\",\"typ" +
				"e\":{\"type\":\"record\",\"name\":\"commodityCodingSystem\",\"namespace\":\"com.maersk.order" +
				"handling.containermain\",\"fields\":[{\"name\":\"commodityCodingSystemCode\",\"doc\":\"The" +
				" uniquely identifying code for the commodity coding system.\",\"type\":\"string\"},{\"" +
				"name\":\"commodityCodingSystemName\",\"doc\":\"The full name of the commodity coding s" +
				"ystem.\",\"type\":\"string\"}]}}]}]},{\"name\":\"commodityCodingSystem\",\"doc\":\"The syste" +
				"m that defines the commodity codes: E.g.: Harmonized System, MARS Commodity code" +
				"s, ...\",\"type\":\"commodityCodingSystem\"}]}]},{\"name\":\"commodityCodingSystem\",\"doc" +
				"\":\"The system that defines the commodity codes: E.g.: Harmonized System, MARS Co" +
				"mmodity codes, ...\",\"type\":\"commodityCodingSystem\"}]}}]}}]}]}}}]}}]}]}}]}");
		/// <summary>
		/// The booking number for the shipment booking
		/// </summary>
		private string _shipmentNumber;
		/// <summary>
		/// INSTANCE_ID for the shipment. It is the primary key for the SHIPMENT table in GCSS
		/// </summary>
		private string _shipmentIdentifier;
		/// <summary>
		/// INSTANCE_ID for the shipment version. It is the primary key for the SHIPMENT_VERSION table in GCSS
		/// </summary>
		private string _shipmentVersionIdentifier;
		private string _shipmentVersionCreatedDatetime;
		private string _shipmentVersionUpdatedDatetime;
		/// <summary>
		/// A timestamp for when any object in the shipment structure was latest updated.
		/// </summary>
		private string _shipmentStructureUpdateDatetime;
		/// <summary>
		/// Identification of the carrier internal to Maersk. - The carrier owning the booking.
		/// </summary>
		private com.maersk.orderhandling.containermain.brand _brand;
		/// <summary>
		/// Information on carriers involved in the transport of the shipment.
		/// </summary>
		private com.maersk.orderhandling.containermain.partyAssociation _partyAssociation;
		/// <summary>
		/// The total number of containers/equipment booked.
		/// </summary>
		private System.Nullable<System.Int32> _totalBookedEquipmentQuantity;
		/// <summary>
		/// The total number of containers/equipment booked equivalent to 40' containers. E.g. If 3 or 4 pieces of 20' containers are booked this attribute is set to 2.
		/// </summary>
		private System.Nullable<System.Int32> _totalBookedEquipmentFFE;
		/// <summary>
		/// The total booked weight of all cargo and equipment.
		/// </summary>
		private System.Nullable<System.Double> _totalBookedGrossWeight;
		/// <summary>
		/// The total booked weight of all cargo and packaging but not including equipment weight.
		/// </summary>
		private System.Nullable<System.Double> _totalBookedNetWeight;
		/// <summary>
		/// The measurement unit of the total booked cargo weight.
		/// </summary>
		private com.maersk.orderhandling.containermain.totalBookedWeightWeightUnit _totalBookedWeightWeightUnit;
		/// <summary>
		/// The total booked volume of all cargo.
		/// </summary>
		private System.Nullable<System.Double> _totalBookedVolume;
		/// <summary>
		/// The measurement unit of the total booked cargo volume.
		/// </summary>
		private com.maersk.orderhandling.containermain.totalBookedVolumeVolumeUnit _totalBookedVolumeVolumeUnit;
		/// <summary>
		/// A container/piece of equipment assigned to the booking.
		/// </summary>
		private com.maersk.orderhandling.containermain.shipmentEquipment _shipmentEquipment;
		public virtual Schema Schema
		{
			get
			{
				return ContainerMain._SCHEMA;
			}
		}
		/// <summary>
		/// The booking number for the shipment booking
		/// </summary>
		public string shipmentNumber
		{
			get
			{
				return this._shipmentNumber;
			}
			set
			{
				this._shipmentNumber = value;
			}
		}
		/// <summary>
		/// INSTANCE_ID for the shipment. It is the primary key for the SHIPMENT table in GCSS
		/// </summary>
		public string shipmentIdentifier
		{
			get
			{
				return this._shipmentIdentifier;
			}
			set
			{
				this._shipmentIdentifier = value;
			}
		}
		/// <summary>
		/// INSTANCE_ID for the shipment version. It is the primary key for the SHIPMENT_VERSION table in GCSS
		/// </summary>
		public string shipmentVersionIdentifier
		{
			get
			{
				return this._shipmentVersionIdentifier;
			}
			set
			{
				this._shipmentVersionIdentifier = value;
			}
		}
		public string shipmentVersionCreatedDatetime
		{
			get
			{
				return this._shipmentVersionCreatedDatetime;
			}
			set
			{
				this._shipmentVersionCreatedDatetime = value;
			}
		}
		public string shipmentVersionUpdatedDatetime
		{
			get
			{
				return this._shipmentVersionUpdatedDatetime;
			}
			set
			{
				this._shipmentVersionUpdatedDatetime = value;
			}
		}
		/// <summary>
		/// A timestamp for when any object in the shipment structure was latest updated.
		/// </summary>
		public string shipmentStructureUpdateDatetime
		{
			get
			{
				return this._shipmentStructureUpdateDatetime;
			}
			set
			{
				this._shipmentStructureUpdateDatetime = value;
			}
		}
		/// <summary>
		/// Identification of the carrier internal to Maersk. - The carrier owning the booking.
		/// </summary>
		public com.maersk.orderhandling.containermain.brand brand
		{
			get
			{
				return this._brand;
			}
			set
			{
				this._brand = value;
			}
		}
		/// <summary>
		/// Information on carriers involved in the transport of the shipment.
		/// </summary>
		public com.maersk.orderhandling.containermain.partyAssociation partyAssociation
		{
			get
			{
				return this._partyAssociation;
			}
			set
			{
				this._partyAssociation = value;
			}
		}
		/// <summary>
		/// The total number of containers/equipment booked.
		/// </summary>
		public System.Nullable<System.Int32> totalBookedEquipmentQuantity
		{
			get
			{
				return this._totalBookedEquipmentQuantity;
			}
			set
			{
				this._totalBookedEquipmentQuantity = value;
			}
		}
		/// <summary>
		/// The total number of containers/equipment booked equivalent to 40' containers. E.g. If 3 or 4 pieces of 20' containers are booked this attribute is set to 2.
		/// </summary>
		public System.Nullable<System.Int32> totalBookedEquipmentFFE
		{
			get
			{
				return this._totalBookedEquipmentFFE;
			}
			set
			{
				this._totalBookedEquipmentFFE = value;
			}
		}
		/// <summary>
		/// The total booked weight of all cargo and equipment.
		/// </summary>
		public System.Nullable<System.Double> totalBookedGrossWeight
		{
			get
			{
				return this._totalBookedGrossWeight;
			}
			set
			{
				this._totalBookedGrossWeight = value;
			}
		}
		/// <summary>
		/// The total booked weight of all cargo and packaging but not including equipment weight.
		/// </summary>
		public System.Nullable<System.Double> totalBookedNetWeight
		{
			get
			{
				return this._totalBookedNetWeight;
			}
			set
			{
				this._totalBookedNetWeight = value;
			}
		}
		/// <summary>
		/// The measurement unit of the total booked cargo weight.
		/// </summary>
		public com.maersk.orderhandling.containermain.totalBookedWeightWeightUnit totalBookedWeightWeightUnit
		{
			get
			{
				return this._totalBookedWeightWeightUnit;
			}
			set
			{
				this._totalBookedWeightWeightUnit = value;
			}
		}
		/// <summary>
		/// The total booked volume of all cargo.
		/// </summary>
		public System.Nullable<System.Double> totalBookedVolume
		{
			get
			{
				return this._totalBookedVolume;
			}
			set
			{
				this._totalBookedVolume = value;
			}
		}
		/// <summary>
		/// The measurement unit of the total booked cargo volume.
		/// </summary>
		public com.maersk.orderhandling.containermain.totalBookedVolumeVolumeUnit totalBookedVolumeVolumeUnit
		{
			get
			{
				return this._totalBookedVolumeVolumeUnit;
			}
			set
			{
				this._totalBookedVolumeVolumeUnit = value;
			}
		}
		/// <summary>
		/// A container/piece of equipment assigned to the booking.
		/// </summary>
		public com.maersk.orderhandling.containermain.shipmentEquipment shipmentEquipment
		{
			get
			{
				return this._shipmentEquipment;
			}
			set
			{
				this._shipmentEquipment = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.shipmentNumber;
			case 1: return this.shipmentIdentifier;
			case 2: return this.shipmentVersionIdentifier;
			case 3: return this.shipmentVersionCreatedDatetime;
			case 4: return this.shipmentVersionUpdatedDatetime;
			case 5: return this.shipmentStructureUpdateDatetime;
			case 6: return this.brand;
			case 7: return this.partyAssociation;
			case 8: return this.totalBookedEquipmentQuantity;
			case 9: return this.totalBookedEquipmentFFE;
			case 10: return this.totalBookedGrossWeight;
			case 11: return this.totalBookedNetWeight;
			case 12: return this.totalBookedWeightWeightUnit;
			case 13: return this.totalBookedVolume;
			case 14: return this.totalBookedVolumeVolumeUnit;
			case 15: return this.shipmentEquipment;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.shipmentNumber = (System.String)fieldValue; break;
			case 1: this.shipmentIdentifier = (System.String)fieldValue; break;
			case 2: this.shipmentVersionIdentifier = (System.String)fieldValue; break;
			case 3: this.shipmentVersionCreatedDatetime = (System.String)fieldValue; break;
			case 4: this.shipmentVersionUpdatedDatetime = (System.String)fieldValue; break;
			case 5: this.shipmentStructureUpdateDatetime = (System.String)fieldValue; break;
			case 6: this.brand = (com.maersk.orderhandling.containermain.brand)fieldValue; break;
			case 7: this.partyAssociation = (com.maersk.orderhandling.containermain.partyAssociation)fieldValue; break;
			case 8: this.totalBookedEquipmentQuantity = (System.Nullable<System.Int32>)fieldValue; break;
			case 9: this.totalBookedEquipmentFFE = (System.Nullable<System.Int32>)fieldValue; break;
			case 10: this.totalBookedGrossWeight = (System.Nullable<System.Double>)fieldValue; break;
			case 11: this.totalBookedNetWeight = (System.Nullable<System.Double>)fieldValue; break;
			case 12: this.totalBookedWeightWeightUnit = (com.maersk.orderhandling.containermain.totalBookedWeightWeightUnit)fieldValue; break;
			case 13: this.totalBookedVolume = (System.Nullable<System.Double>)fieldValue; break;
			case 14: this.totalBookedVolumeVolumeUnit = (com.maersk.orderhandling.containermain.totalBookedVolumeVolumeUnit)fieldValue; break;
			case 15: this.shipmentEquipment = (com.maersk.orderhandling.containermain.shipmentEquipment)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
