// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class equipmentSizeType : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"equipmentSizeType\",\"namespace\":\"com.maersk.orderhandling" +
				".containermain\",\"fields\":[{\"name\":\"sizeTypeCode\",\"doc\":\"The ISO code for the siz" +
				"e and type.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"description\",\"doc" +
				"\":\"A description of the container size and type.\",\"type\":\"string\"},{\"name\":\"equi" +
				"pmentSize\",\"doc\":\"The Maersk code for container length (size).\",\"type\":{\"type\":\"" +
				"record\",\"name\":\"equipmentSize\",\"namespace\":\"com.maersk.orderhandling.containerma" +
				"in\",\"fields\":[{\"name\":\"equipmentSizeCode\",\"doc\":\"The Maersk container length (si" +
				"ze) code.\",\"type\":\"string\"},{\"name\":\"equipmentSizeName\",\"doc\":\"The Maersk contai" +
				"ner length (size).\",\"type\":\"string\"}]}},{\"name\":\"equipmentHeight\",\"doc\":\"The Mae" +
				"rsk code for container height.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"" +
				"name\":\"equipmentHeight\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fi" +
				"elds\":[{\"name\":\"equipmentHeightCode\",\"doc\":\"The Maersk code for container height" +
				".\",\"type\":\"string\"},{\"name\":\"equipmentHeightName\",\"doc\":\"The Maersk container he" +
				"ight.\",\"type\":\"string\"}]}]},{\"name\":\"equipmentType\",\"doc\":\"The Maersk descriptio" +
				"n of type of equipment.\",\"type\":{\"type\":\"record\",\"name\":\"equipmentType\",\"namespa" +
				"ce\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"equipmentTypeCod" +
				"e\",\"doc\":\"The Maersk code for equipment type.\",\"type\":\"string\"},{\"name\":\"equipme" +
				"ntTypeName\",\"doc\":\"The Maersk name for equipment type.\",\"default\":null,\"type\":[\"" +
				"null\",\"string\"]},{\"name\":\"equipmentTypeChildEquipmentType\",\"doc\":\"Subtype descri" +
				"ption of the container type. This is upper level of the recursion level 0. It is" +
				" not spelled out here to allow the Avro schema to be backward and forward compli" +
				"ant.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"equipmentTypeChildE" +
				"quipmentType\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"n" +
				"ame\":\"equipmentTypeCode\",\"doc\":\"The Maersk code for equipment type.\",\"type\":\"str" +
				"ing\"},{\"name\":\"equipmentTypeName\",\"doc\":\"The Maersk name for equipment type.\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"equipmentTypeChildEquipmentTypeL" +
				"1\",\"doc\":\"Subtype description of the container type. This is lower level of the " +
				"recursion level 1.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"equip" +
				"mentTypeChildEquipmentTypeL1\",\"namespace\":\"com.maersk.orderhandling.containermai" +
				"n\",\"fields\":[{\"name\":\"equipmentTypeCode\",\"doc\":\"The Maersk code for equipment ty" +
				"pe.\",\"type\":\"string\"},{\"name\":\"equipmentTypeName\",\"doc\":\"The Maersk name for equ" +
				"ipment type.\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]}]}]}]}}]}");
		/// <summary>
		/// The ISO code for the size and type.
		/// </summary>
		private string _sizeTypeCode;
		/// <summary>
		/// A description of the container size and type.
		/// </summary>
		private string _description;
		/// <summary>
		/// The Maersk code for container length (size).
		/// </summary>
		private com.maersk.orderhandling.containermain.equipmentSize _equipmentSize;
		/// <summary>
		/// The Maersk code for container height.
		/// </summary>
		private com.maersk.orderhandling.containermain.equipmentHeight _equipmentHeight;
		/// <summary>
		/// The Maersk description of type of equipment.
		/// </summary>
		private com.maersk.orderhandling.containermain.equipmentType _equipmentType;
		public virtual Schema Schema
		{
			get
			{
				return equipmentSizeType._SCHEMA;
			}
		}
		/// <summary>
		/// The ISO code for the size and type.
		/// </summary>
		public string sizeTypeCode
		{
			get
			{
				return this._sizeTypeCode;
			}
			set
			{
				this._sizeTypeCode = value;
			}
		}
		/// <summary>
		/// A description of the container size and type.
		/// </summary>
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				this._description = value;
			}
		}
		/// <summary>
		/// The Maersk code for container length (size).
		/// </summary>
		public com.maersk.orderhandling.containermain.equipmentSize equipmentSize
		{
			get
			{
				return this._equipmentSize;
			}
			set
			{
				this._equipmentSize = value;
			}
		}
		/// <summary>
		/// The Maersk code for container height.
		/// </summary>
		public com.maersk.orderhandling.containermain.equipmentHeight equipmentHeight
		{
			get
			{
				return this._equipmentHeight;
			}
			set
			{
				this._equipmentHeight = value;
			}
		}
		/// <summary>
		/// The Maersk description of type of equipment.
		/// </summary>
		public com.maersk.orderhandling.containermain.equipmentType equipmentType
		{
			get
			{
				return this._equipmentType;
			}
			set
			{
				this._equipmentType = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.sizeTypeCode;
			case 1: return this.description;
			case 2: return this.equipmentSize;
			case 3: return this.equipmentHeight;
			case 4: return this.equipmentType;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.sizeTypeCode = (System.String)fieldValue; break;
			case 1: this.description = (System.String)fieldValue; break;
			case 2: this.equipmentSize = (com.maersk.orderhandling.containermain.equipmentSize)fieldValue; break;
			case 3: this.equipmentHeight = (com.maersk.orderhandling.containermain.equipmentHeight)fieldValue; break;
			case 4: this.equipmentType = (com.maersk.orderhandling.containermain.equipmentType)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
