// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class equipmentProfile : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""equipmentProfile"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""equipmentProfileCode"",""doc"":""The container type code."",""default"":null,""type"":[""null"",""string""]},{""name"":""equipmentProfileName"",""doc"":""The Maersk container type name."",""type"":""string""}]}");
		/// <summary>
		/// The container type code.
		/// </summary>
		private string _equipmentProfileCode;
		/// <summary>
		/// The Maersk container type name.
		/// </summary>
		private string _equipmentProfileName;
		public virtual Schema Schema
		{
			get
			{
				return equipmentProfile._SCHEMA;
			}
		}
		/// <summary>
		/// The container type code.
		/// </summary>
		public string equipmentProfileCode
		{
			get
			{
				return this._equipmentProfileCode;
			}
			set
			{
				this._equipmentProfileCode = value;
			}
		}
		/// <summary>
		/// The Maersk container type name.
		/// </summary>
		public string equipmentProfileName
		{
			get
			{
				return this._equipmentProfileName;
			}
			set
			{
				this._equipmentProfileName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.equipmentProfileCode;
			case 1: return this.equipmentProfileName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.equipmentProfileCode = (System.String)fieldValue; break;
			case 1: this.equipmentProfileName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
