// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class equipmentSize : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""equipmentSize"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""equipmentSizeCode"",""doc"":""The Maersk container length (size) code."",""type"":""string""},{""name"":""equipmentSizeName"",""doc"":""The Maersk container length (size)."",""type"":""string""}]}");
		/// <summary>
		/// The Maersk container length (size) code.
		/// </summary>
		private string _equipmentSizeCode;
		/// <summary>
		/// The Maersk container length (size).
		/// </summary>
		private string _equipmentSizeName;
		public virtual Schema Schema
		{
			get
			{
				return equipmentSize._SCHEMA;
			}
		}
		/// <summary>
		/// The Maersk container length (size) code.
		/// </summary>
		public string equipmentSizeCode
		{
			get
			{
				return this._equipmentSizeCode;
			}
			set
			{
				this._equipmentSizeCode = value;
			}
		}
		/// <summary>
		/// The Maersk container length (size).
		/// </summary>
		public string equipmentSizeName
		{
			get
			{
				return this._equipmentSizeName;
			}
			set
			{
				this._equipmentSizeName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.equipmentSizeCode;
			case 1: return this.equipmentSizeName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.equipmentSizeCode = (System.String)fieldValue; break;
			case 1: this.equipmentSizeName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
