// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class imDgPackageType : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""imDgPackageType"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""imDgPackageTypeCode"",""doc"":""The International Maritime Dangerous Goods code (Up to 5 characters). E.g.: 11HA2, 1A1."",""type"":""string""},{""name"":""imDgPackageTypeName"",""doc"":""The packaging type name."",""type"":""string""},{""name"":""imDgPackageTypeDescription"",""doc"":""A text describing the package type."",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// The International Maritime Dangerous Goods code (Up to 5 characters). E.g.: 11HA2, 1A1.
		/// </summary>
		private string _imDgPackageTypeCode;
		/// <summary>
		/// The packaging type name.
		/// </summary>
		private string _imDgPackageTypeName;
		/// <summary>
		/// A text describing the package type.
		/// </summary>
		private string _imDgPackageTypeDescription;
		public virtual Schema Schema
		{
			get
			{
				return imDgPackageType._SCHEMA;
			}
		}
		/// <summary>
		/// The International Maritime Dangerous Goods code (Up to 5 characters). E.g.: 11HA2, 1A1.
		/// </summary>
		public string imDgPackageTypeCode
		{
			get
			{
				return this._imDgPackageTypeCode;
			}
			set
			{
				this._imDgPackageTypeCode = value;
			}
		}
		/// <summary>
		/// The packaging type name.
		/// </summary>
		public string imDgPackageTypeName
		{
			get
			{
				return this._imDgPackageTypeName;
			}
			set
			{
				this._imDgPackageTypeName = value;
			}
		}
		/// <summary>
		/// A text describing the package type.
		/// </summary>
		public string imDgPackageTypeDescription
		{
			get
			{
				return this._imDgPackageTypeDescription;
			}
			set
			{
				this._imDgPackageTypeDescription = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.imDgPackageTypeCode;
			case 1: return this.imDgPackageTypeName;
			case 2: return this.imDgPackageTypeDescription;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.imDgPackageTypeCode = (System.String)fieldValue; break;
			case 1: this.imDgPackageTypeName = (System.String)fieldValue; break;
			case 2: this.imDgPackageTypeDescription = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
