// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class oceanCarrier : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""oceanCarrier"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""partyRoleTypeName"",""doc"":""The type of party relating to the transport."",""type"":""string""},{""name"":""standardCarrierAlphaCode"",""doc"":""The official operator code for the carrier/operator where the shipment is booked"",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// The type of party relating to the transport.
		/// </summary>
		private string _partyRoleTypeName;
		/// <summary>
		/// The official operator code for the carrier/operator where the shipment is booked
		/// </summary>
		private string _standardCarrierAlphaCode;
		public virtual Schema Schema
		{
			get
			{
				return oceanCarrier._SCHEMA;
			}
		}
		/// <summary>
		/// The type of party relating to the transport.
		/// </summary>
		public string partyRoleTypeName
		{
			get
			{
				return this._partyRoleTypeName;
			}
			set
			{
				this._partyRoleTypeName = value;
			}
		}
		/// <summary>
		/// The official operator code for the carrier/operator where the shipment is booked
		/// </summary>
		public string standardCarrierAlphaCode
		{
			get
			{
				return this._standardCarrierAlphaCode;
			}
			set
			{
				this._standardCarrierAlphaCode = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.partyRoleTypeName;
			case 1: return this.standardCarrierAlphaCode;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.partyRoleTypeName = (System.String)fieldValue; break;
			case 1: this.standardCarrierAlphaCode = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
