// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class partyAssociation : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""partyAssociation"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""oceanCarrier"",""doc"":""Information on the company performing the transport at sea."",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""oceanCarrier"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""partyRoleTypeName"",""doc"":""The type of party relating to the transport."",""type"":""string""},{""name"":""standardCarrierAlphaCode"",""doc"":""The official operator code for the carrier/operator where the shipment is booked"",""default"":null,""type"":[""null"",""string""]}]}]}]}");
		/// <summary>
		/// Information on the company performing the transport at sea.
		/// </summary>
		private com.maersk.orderhandling.containermain.oceanCarrier _oceanCarrier;
		public virtual Schema Schema
		{
			get
			{
				return partyAssociation._SCHEMA;
			}
		}
		/// <summary>
		/// Information on the company performing the transport at sea.
		/// </summary>
		public com.maersk.orderhandling.containermain.oceanCarrier oceanCarrier
		{
			get
			{
				return this._oceanCarrier;
			}
			set
			{
				this._oceanCarrier = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.oceanCarrier;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.oceanCarrier = (com.maersk.orderhandling.containermain.oceanCarrier)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
