// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class shipmentEquipmentSubstituesOrReplaces : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""shipmentEquipmentSubstituesOrReplaces"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""shipmentEquipmentIdentifier"",""doc"":""A unique identifier of the equipment that is substituted/replaced - (INSTANCE_ID in GCSS)."",""type"":""string""}]}");
		/// <summary>
		/// A unique identifier of the equipment that is substituted/replaced - (INSTANCE_ID in GCSS).
		/// </summary>
		private string _shipmentEquipmentIdentifier;
		public virtual Schema Schema
		{
			get
			{
				return shipmentEquipmentSubstituesOrReplaces._SCHEMA;
			}
		}
		/// <summary>
		/// A unique identifier of the equipment that is substituted/replaced - (INSTANCE_ID in GCSS).
		/// </summary>
		public string shipmentEquipmentIdentifier
		{
			get
			{
				return this._shipmentEquipmentIdentifier;
			}
			set
			{
				this._shipmentEquipmentIdentifier = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.shipmentEquipmentIdentifier;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.shipmentEquipmentIdentifier = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
