// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// One cargo item stuffed in equipment/container and transported by the shipment.
	/// </summary>
	public partial class shipmentLine : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"shipmentLine\",\"doc\":\"One cargo item stuffed in equipment" +
				"/container and transported by the shipment.\",\"namespace\":\"com.maersk.orderhandli" +
				"ng.containermain\",\"fields\":[{\"name\":\"shipmentLineIdentifier\",\"doc\":\"Identificati" +
				"on of the unique cargo that is stuffed in the container. The CARGO INSTANCE_ID f" +
				"rom GCSS database.\",\"type\":\"string\"},{\"name\":\"commodityClassificationAssociation" +
				"s\",\"doc\":\"A list classifying the cargo in commodity types provided by customer.\"" +
				",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"" +
				"commodityClassificationAssociation\",\"namespace\":\"com.maersk.orderhandling.contai" +
				"nermain\",\"fields\":[{\"name\":\"commodityCode\",\"doc\":\"A customer provided non-standa" +
				"rdized commodity code.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"commod" +
				"ityName\",\"doc\":\"A customer provided non-standardized commodity name.\",\"default\":" +
				"null,\"type\":[\"null\",\"string\"]},{\"name\":\"commodityClassification\",\"doc\":\"Standard" +
				"ized commodity classification information.\",\"type\":{\"type\":\"record\",\"name\":\"comm" +
				"odityClassification\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"field" +
				"s\":[{\"name\":\"commodityGroup\",\"doc\":\"The commodity category type.\",\"default\":null" +
				",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityGroup\",\"namespace\":\"com.maersk" +
				".orderhandling.containermain\",\"fields\":[{\"name\":\"commodityGroupCode\",\"doc\":\"The " +
				"identifying code for the commodity category.\",\"type\":\"string\"},{\"name\":\"commodit" +
				"yGroupName\",\"doc\":\"The full name of the commodity category.\",\"type\":\"string\"}]}]" +
				"},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the commodity.\",\"type\":\"string\"" +
				"},{\"name\":\"commodityName\",\"doc\":\"A textual description of the commodity.\",\"type\"" +
				":\"string\"},{\"name\":\"commodityClassificationChild\",\"doc\":\"A sub category commodit" +
				"y description. This is the top level of the recursion level 0 not written out he" +
				"re to keep the Avro schema backward and forward compatible.\",\"default\":null,\"typ" +
				"e\":[\"null\",{\"type\":\"record\",\"name\":\"commodityClassificationChild\",\"namespace\":\"c" +
				"om.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodityGroup\",\"doc\":" +
				"\"The commodity category type.\",\"default\":null,\"type\":[\"null\",\"commodityGroup\"]}," +
				"{\"name\":\"commodityCode\",\"doc\":\"The HS code for the commodity.\",\"type\":\"string\"}," +
				"{\"name\":\"commodityName\",\"doc\":\"A textual description of the commodity.\",\"type\":\"" +
				"string\"},{\"name\":\"commodityClassificationChildL1\",\"doc\":\"A sub category commodit" +
				"y description. The lower level of the recursion.\",\"default\":null,\"type\":[\"null\"," +
				"{\"type\":\"record\",\"name\":\"commodityClassificationChildL1\",\"namespace\":\"com.maersk" +
				".orderhandling.containermain\",\"fields\":[{\"name\":\"commodityGroup\",\"doc\":\"The comm" +
				"odity category type.\",\"default\":null,\"type\":[\"null\",\"commodityGroup\"]},{\"name\":\"" +
				"commodityCode\",\"doc\":\"The HS code for the commodity.\",\"type\":\"string\"},{\"name\":\"" +
				"commodityName\",\"doc\":\"A textual description of the commodity.\",\"type\":\"string\"}," +
				"{\"name\":\"commodityCodingSystem\",\"doc\":\"The system that defines the commodity cod" +
				"es: E.g.: Harmonized System, MARS Commodity codes, ...\",\"type\":{\"type\":\"record\"," +
				"\"name\":\"commodityCodingSystem\",\"namespace\":\"com.maersk.orderhandling.containerma" +
				"in\",\"fields\":[{\"name\":\"commodityCodingSystemCode\",\"doc\":\"The uniquely identifyin" +
				"g code for the commodity coding system.\",\"type\":\"string\"},{\"name\":\"commodityCodi" +
				"ngSystemName\",\"doc\":\"The full name of the commodity coding system.\",\"type\":\"stri" +
				"ng\"}]}}]}]},{\"name\":\"commodityCodingSystem\",\"doc\":\"The system that defines the c" +
				"ommodity codes: E.g.: Harmonized System, MARS Commodity codes, ...\",\"type\":\"comm" +
				"odityCodingSystem\"}]}]},{\"name\":\"commodityCodingSystem\",\"doc\":\"The system that d" +
				"efines the commodity codes: E.g.: Harmonized System, MARS Commodity codes, ...\"," +
				"\"type\":\"commodityCodingSystem\"}]}}]}}]}]}");
		/// <summary>
		/// Identification of the unique cargo that is stuffed in the container. The CARGO INSTANCE_ID from GCSS database.
		/// </summary>
		private string _shipmentLineIdentifier;
		/// <summary>
		/// A list classifying the cargo in commodity types provided by customer.
		/// </summary>
		private IList<com.maersk.orderhandling.containermain.commodityClassificationAssociation> _commodityClassificationAssociations;
		public virtual Schema Schema
		{
			get
			{
				return shipmentLine._SCHEMA;
			}
		}
		/// <summary>
		/// Identification of the unique cargo that is stuffed in the container. The CARGO INSTANCE_ID from GCSS database.
		/// </summary>
		public string shipmentLineIdentifier
		{
			get
			{
				return this._shipmentLineIdentifier;
			}
			set
			{
				this._shipmentLineIdentifier = value;
			}
		}
		/// <summary>
		/// A list classifying the cargo in commodity types provided by customer.
		/// </summary>
		public IList<com.maersk.orderhandling.containermain.commodityClassificationAssociation> commodityClassificationAssociations
		{
			get
			{
				return this._commodityClassificationAssociations;
			}
			set
			{
				this._commodityClassificationAssociations = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.shipmentLineIdentifier;
			case 1: return this.commodityClassificationAssociations;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.shipmentLineIdentifier = (System.String)fieldValue; break;
			case 1: this.commodityClassificationAssociations = (IList<com.maersk.orderhandling.containermain.commodityClassificationAssociation>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
