// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class shipmentEquipment : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"shipmentEquipment\",\"namespace\":\"com.maersk.orderhandling" +
				".containermain\",\"fields\":[{\"name\":\"shipmentEquipmentIdentifier\",\"doc\":\"A unique " +
				"identifier of the equipment assignment - (INSTANCE_ID in GCSS).\",\"type\":\"string\"" +
				"},{\"name\":\"container\",\"doc\":\"A description of the equipment assigned. - Only ava" +
				"ilable when equipment has been matched to booking.\",\"default\":null,\"type\":[\"null" +
				"\",{\"type\":\"record\",\"name\":\"container\",\"namespace\":\"com.maersk.orderhandling.cont" +
				"ainermain\",\"fields\":[{\"name\":\"isoCombinedCode\",\"doc\":\"The full ISO 6346 standard" +
				"ised container identification code.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"" +
				"name\":\"isoOwnerCode\",\"doc\":\"The owning company\'s ISO 6346 code.\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]},{\"name\":\"isoCategoryCode\",\"doc\":\"The equipment type IS" +
				"O 6346 category code - this will be \'U\'.\",\"default\":null,\"type\":[\"null\",\"string\"" +
				"]},{\"name\":\"isoSerialNumber\",\"doc\":\"The ISO 6346 equipment identification code s" +
				"erial number part.\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"isoCheckDigit" +
				"Number\",\"doc\":\"The ISO 6346 equipment identification code check digit.\",\"default" +
				"\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"equipmentSizeType\",\"doc\":\"A classificatio" +
				"n of size and type of the container.\",\"type\":{\"type\":\"record\",\"name\":\"equipmentS" +
				"izeType\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":" +
				"\"sizeTypeCode\",\"doc\":\"The ISO code for the size and type.\",\"default\":null,\"type\"" +
				":[\"null\",\"string\"]},{\"name\":\"description\",\"doc\":\"A description of the container " +
				"size and type.\",\"type\":\"string\"},{\"name\":\"equipmentSize\",\"doc\":\"The Maersk code " +
				"for container length (size).\",\"type\":{\"type\":\"record\",\"name\":\"equipmentSize\",\"na" +
				"mespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"equipmentSi" +
				"zeCode\",\"doc\":\"The Maersk container length (size) code.\",\"type\":\"string\"},{\"name" +
				"\":\"equipmentSizeName\",\"doc\":\"The Maersk container length (size).\",\"type\":\"string" +
				"\"}]}},{\"name\":\"equipmentHeight\",\"doc\":\"The Maersk code for container height.\",\"d" +
				"efault\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"equipmentHeight\",\"namespace" +
				"\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"equipmentHeightCod" +
				"e\",\"doc\":\"The Maersk code for container height.\",\"type\":\"string\"},{\"name\":\"equip" +
				"mentHeightName\",\"doc\":\"The Maersk container height.\",\"type\":\"string\"}]}]},{\"name" +
				"\":\"equipmentType\",\"doc\":\"The Maersk description of type of equipment.\",\"type\":{\"" +
				"type\":\"record\",\"name\":\"equipmentType\",\"namespace\":\"com.maersk.orderhandling.cont" +
				"ainermain\",\"fields\":[{\"name\":\"equipmentTypeCode\",\"doc\":\"The Maersk code for equi" +
				"pment type.\",\"type\":\"string\"},{\"name\":\"equipmentTypeName\",\"doc\":\"The Maersk name" +
				" for equipment type.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"equipmen" +
				"tTypeChildEquipmentType\",\"doc\":\"Subtype description of the container type. This " +
				"is upper level of the recursion level 0. It is not spelled out here to allow the" +
				" Avro schema to be backward and forward compliant.\",\"default\":null,\"type\":[\"null" +
				"\",{\"type\":\"record\",\"name\":\"equipmentTypeChildEquipmentType\",\"namespace\":\"com.mae" +
				"rsk.orderhandling.containermain\",\"fields\":[{\"name\":\"equipmentTypeCode\",\"doc\":\"Th" +
				"e Maersk code for equipment type.\",\"type\":\"string\"},{\"name\":\"equipmentTypeName\"," +
				"\"doc\":\"The Maersk name for equipment type.\",\"default\":null,\"type\":[\"null\",\"strin" +
				"g\"]},{\"name\":\"equipmentTypeChildEquipmentTypeL1\",\"doc\":\"Subtype description of t" +
				"he container type. This is lower level of the recursion level 1.\",\"default\":null" +
				",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"equipmentTypeChildEquipmentTypeL1\",\"nam" +
				"espace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"equipmentTyp" +
				"eCode\",\"doc\":\"The Maersk code for equipment type.\",\"type\":\"string\"},{\"name\":\"equ" +
				"ipmentTypeName\",\"doc\":\"The Maersk name for equipment type.\",\"default\":null,\"type" +
				"\":[\"null\",\"string\"]}]}]}]}]}]}}]}},{\"name\":\"alternativeCodes\",\"default\":null,\"ty" +
				"pe\":[\"null\",{\"type\":\"record\",\"name\":\"alternativeCodes\",\"namespace\":\"com.maersk.o" +
				"rderhandling.containermain\",\"fields\":[{\"name\":\"ALTERNATIVE_CONTAINER_IDENTIFIER\"" +
				",\"doc\":\"An alternative identification code of the equipment - usually provided f" +
				"rom customer when container is customer owned.\",\"default\":null,\"type\":[\"null\",\"s" +
				"tring\"]}]}]}]}]},{\"name\":\"equipmentProfile\",\"doc\":\"Specifies the type of reefer " +
				"container to be used for the transport.\",\"default\":null,\"type\":[\"null\",{\"type\":\"" +
				"record\",\"name\":\"equipmentProfile\",\"namespace\":\"com.maersk.orderhandling.containe" +
				"rmain\",\"fields\":[{\"name\":\"equipmentProfileCode\",\"doc\":\"The container type code.\"" +
				",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"equipmentProfileName\",\"doc\":\"" +
				"The Maersk container type name.\",\"type\":\"string\"}]}]},{\"name\":\"cargoPackageType\"" +
				",\"doc\":\"The style of packaging used in the container/equipment.\",\"default\":null," +
				"\"type\":[\"null\",{\"type\":\"record\",\"name\":\"cargoPackageType\",\"namespace\":\"com.maers" +
				"k.orderhandling.containermain\",\"fields\":[{\"name\":\"cargoPackageTypeCode\",\"doc\":\"A" +
				" standardised code for the packing style.\",\"default\":null,\"type\":[\"null\",\"string" +
				"\"]},{\"name\":\"cargoPackageTypeName\",\"doc\":\"A standardised cargo packaging style n" +
				"ame.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"cargoPackageTypeDescript" +
				"ion\",\"doc\":\"A textual description of the cargo packaging style.\",\"default\":null," +
				"\"type\":[\"null\",\"string\"]},{\"name\":\"alternativeCodes\",\"doc\":\"A list of alternativ" +
				"e cargo package type codes.\",\"default\":null,\"type\":[\"null\",{\"type\":\"array\",\"item" +
				"s\":{\"type\":\"record\",\"name\":\"alternativeCode\",\"doc\":\"An alternative cargo package" +
				" type code.\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"na" +
				"me\":\"alternativeCode\",\"doc\":\"Alternative code type code.\",\"type\":\"string\"},{\"nam" +
				"e\":\"unPackageType\",\"doc\":\"The United Nations standardised code for a package typ" +
				"e. If any alternative package type code exists - this should be always be specif" +
				"ied.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"unPackageType\",\"nam" +
				"espace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"unPackageTyp" +
				"eCode\",\"doc\":\"The United Nations standardized cargo package type code.\",\"type\":\"" +
				"string\"},{\"name\":\"unPackageTypeName\",\"doc\":\"The name of the United Nations stand" +
				"ardized cargo package type.\",\"type\":\"string\"},{\"name\":\"unPackageTypeDescription\"" +
				",\"doc\":\"A description of the United Nations standardized cargo package type.\",\"d" +
				"efault\":null,\"type\":[\"null\",\"string\"]}]}]},{\"name\":\"imDgPackageType\",\"doc\":\"Pack" +
				"age types specifically described for hazardous cargo.\",\"default\":null,\"type\":[\"n" +
				"ull\",{\"type\":\"record\",\"name\":\"imDgPackageType\",\"namespace\":\"com.maersk.orderhand" +
				"ling.containermain\",\"fields\":[{\"name\":\"imDgPackageTypeCode\",\"doc\":\"The Internati" +
				"onal Maritime Dangerous Goods code (Up to 5 characters). E.g.: 11HA2, 1A1.\",\"typ" +
				"e\":\"string\"},{\"name\":\"imDgPackageTypeName\",\"doc\":\"The packaging type name.\",\"typ" +
				"e\":\"string\"},{\"name\":\"imDgPackageTypeDescription\",\"doc\":\"A text describing the p" +
				"ackage type.\",\"default\":null,\"type\":[\"null\",\"string\"]}]}]}]}}]}]}]},{\"name\":\"tot" +
				"alStuffedPackageQuantity\",\"doc\":\"Total number of outer level packages stuffed in" +
				" the container/equipment.\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"totalS" +
				"tuffedCustomerProductQuantity\",\"doc\":\"Total number of products stuffed in the co" +
				"ntainer/equipment.\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"totalStuffedG" +
				"rossWeight\",\"doc\":\"The total weight of all cargo stuffed in the container/equipm" +
				"ent including outer level packaging.\",\"default\":null,\"type\":[\"null\",\"double\"]},{" +
				"\"name\":\"totalStuffedNetWeight\",\"doc\":\"The total net weight of all cargo stuffed " +
				"in the container excluding outer level packaging.\",\"default\":null,\"type\":[\"null\"" +
				",\"double\"]},{\"name\":\"totalStuffedWeightWeightUnit\",\"doc\":\"The measurement unit o" +
				"f the total stuffed cargo weight in container/equipment.\",\"default\":null,\"type\":" +
				"[\"null\",{\"type\":\"record\",\"name\":\"totalStuffedWeightWeightUnit\",\"namespace\":\"com." +
				"maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"unitOfMeasurementCode\",\"d" +
				"oc\":\"The measurement code - E.g.: KGS, Metric Ton, US LBS.\",\"type\":\"string\"},{\"n" +
				"ame\":\"unitOfMeasurementName\",\"doc\":\"The full name of the measurement unit.\",\"typ" +
				"e\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicator for the measurement sy" +
				"stem used.\",\"type\":{\"type\":\"record\",\"name\":\"measurementSystem\",\"namespace\":\"com." +
				"maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"measurementSystemCode\",\"d" +
				"oc\":\"The abbreviated measure system name. - E.g.: S.I. (Metric), Imperial, US Cu" +
				"stomary Units, Time, Industry Standard.\",\"type\":\"string\"},{\"name\":\"measurementSy" +
				"stemName\",\"doc\":\"The full measure system name.\",\"type\":\"string\"}]}}]}]},{\"name\":" +
				"\"totalStuffedVolume\",\"doc\":\"The total volume of cargo stuffed in the container/e" +
				"quipment.\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"totalStuffedVolumeV" +
				"olumeUnit\",\"doc\":\"The measurement unit of the total stuffed cargo volume in the " +
				"container/equipment.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"tot" +
				"alStuffedVolumeVolumeUnit\",\"namespace\":\"com.maersk.orderhandling.containermain\"," +
				"\"fields\":[{\"name\":\"unitOfMeasurementCode\",\"doc\":\"The measurement code - E.g.: CB" +
				"M, CBF.\",\"type\":\"string\"},{\"name\":\"unitOfMeasurementName\",\"doc\":\"The full name o" +
				"f the measurement unit.\",\"type\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Ind" +
				"icator for the measurement system used.\",\"type\":\"measurementSystem\"}]}]},{\"name\"" +
				":\"isShipperOwned\",\"doc\":\"Indicates if equipment is owned by the customer/shipper" +
				".\",\"type\":\"boolean\"},{\"name\":\"isSubstituted\",\"doc\":\"Indicates if this equipment/" +
				"container has been replaced by another equipment/container of different size and" +
				"/or type.\",\"type\":\"boolean\"},{\"name\":\"isSubstitution\",\"doc\":\"Indicates of this e" +
				"quipment/container has replaced another equipment/container but has different si" +
				"ze and/or type properties than the equipment/container originally assigned to th" +
				"e shipment.\",\"type\":\"boolean\"},{\"name\":\"isReplaced\",\"doc\":\"Indicates if this equ" +
				"ipment/container has been replaced by another equipment/container of same size a" +
				"nd type.\",\"type\":\"boolean\"},{\"name\":\"isReplacement\",\"doc\":\"Indicates of this equ" +
				"ipment/container has replaced another equipment/container of same size and type." +
				"\",\"type\":\"boolean\"},{\"name\":\"shipmentEquipmentSubstituesOrReplaces\",\"doc\":\"The e" +
				"quipment/container being substituted/replaced by the equipment/container that th" +
				"is event is about.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"shipm" +
				"entEquipmentSubstituesOrReplaces\",\"namespace\":\"com.maersk.orderhandling.containe" +
				"rmain\",\"fields\":[{\"name\":\"shipmentEquipmentIdentifier\",\"doc\":\"A unique identifie" +
				"r of the equipment that is substituted/replaced - (INSTANCE_ID in GCSS).\",\"type\"" +
				":\"string\"}]}]},{\"name\":\"shipmentEquipmentCargoDistributions\",\"doc\":\"Description " +
				"of cargo stuffing/distribution(s) in the container.\",\"default\":null,\"type\":[\"nul" +
				"l\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"shipmentEquipmentCargoDistri" +
				"bution\",\"doc\":\"A description of a single cargo piece stuffing/distribution in th" +
				"e container.\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"n" +
				"ame\":\"shipmentEquipmentCargoDistributionIdentifier\",\"doc\":\"A unique identifier o" +
				"f the stuffing entity. Taken from EQUIPMENT_STUFFING INSTANCE_ID in GCSS databas" +
				"e.\",\"type\":\"string\"},{\"name\":\"cargoPackageType\",\"doc\":\"The style of packaging us" +
				"ed in the container/equipment.\",\"default\":null,\"type\":[\"null\",\"cargoPackageType\"" +
				"]},{\"name\":\"shipmentEquipmentCargoDistributionStatus\",\"doc\":\"Indicates whether t" +
				"he stuffing is planned or actual.\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"enum\"," +
				"\"name\":\"shipmentEquipmentCargoDistributionStatus\",\"namespace\":\"com.maersk.orderh" +
				"andling.containermain\",\"symbols\":[\"PLANNING\",\"ACTUAL\"]}}},{\"name\":\"stuffedPackag" +
				"eQuantity\",\"doc\":\"The number of outermost cargo packages in stuffing.\",\"default\"" +
				":null,\"type\":[\"null\",\"long\"]},{\"name\":\"stuffedCustomerProductQuantity\",\"doc\":\"Th" +
				"e number of customer products in stuffing.\",\"default\":null,\"type\":[\"null\",\"long\"" +
				"]},{\"name\":\"stuffedGrossWeight\",\"doc\":\"The weight of cargo stuffed including out" +
				"er packaging materials and palettes.\",\"default\":null,\"type\":[\"null\",\"double\"]},{" +
				"\"name\":\"stuffedNetWeight\",\"doc\":\"The weight of cargo stuffed excluding outer pac" +
				"kaging materials and palettes.\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\"" +
				":\"stuffedWeightWeightUnit\",\"doc\":\"The measurement unit of the stuffed cargo gros" +
				"s weight.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"weightWeightUn" +
				"it\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"unit" +
				"OfMeasurementCode\",\"doc\":\"The measurement code - E.g.: KGS, Metric Ton, US LBS.\"" +
				",\"type\":\"string\"},{\"name\":\"unitOfMeasurementName\",\"doc\":\"The full name of the me" +
				"asurement unit.\",\"type\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicator f" +
				"or the measurement system used.\",\"type\":\"measurementSystem\"}]}]},{\"name\":\"stuffe" +
				"dVolume\",\"doc\":\"The volume of cargo stuffed including packaging materials and pa" +
				"lettes.\",\"default\":null,\"type\":[\"null\",\"double\"]},{\"name\":\"stuffedVolumeVolumeUn" +
				"it\",\"doc\":\"The measurement unit of the gross stuffed cargo volume.\",\"default\":nu" +
				"ll,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"stuffedVolumeVolumeUnit\",\"namespace\":" +
				"\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"unitOfMeasurementCod" +
				"e\",\"doc\":\"The measurement code - E.g.: Litre, Gallon, Cubic Metres.\",\"type\":\"str" +
				"ing\"},{\"name\":\"unitOfMeasurementName\",\"doc\":\"The full name of the measurement un" +
				"it.\",\"type\":\"string\"},{\"name\":\"measurementSystem\",\"doc\":\"Indicator for the measu" +
				"rement system used.\",\"type\":\"measurementSystem\"}]}]},{\"name\":\"isOutOfGauge\",\"doc" +
				"\":\"Indicate when the stuffed cargo is bigger than what can normally be stuffed i" +
				"n the given equipment/container size.\",\"default\":false,\"type\":\"boolean\"},{\"name\"" +
				":\"isStuffingConfirmed\",\"doc\":\"Flag indicating whether the physical stuffing of t" +
				"he cargo has completed.\",\"default\":true,\"type\":\"boolean\"},{\"name\":\"shipmentLines" +
				"\",\"doc\":\"The cargo(s) stuffed in equipment/container and transported by the ship" +
				"ment.\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"shipmentLine\",\"do" +
				"c\":\"One cargo item stuffed in equipment/container and transported by the shipmen" +
				"t.\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"ship" +
				"mentLineIdentifier\",\"doc\":\"Identification of the unique cargo that is stuffed in" +
				" the container. The CARGO INSTANCE_ID from GCSS database.\",\"type\":\"string\"},{\"na" +
				"me\":\"commodityClassificationAssociations\",\"doc\":\"A list classifying the cargo in" +
				" commodity types provided by customer.\",\"default\":null,\"type\":[\"null\",{\"type\":\"a" +
				"rray\",\"items\":{\"type\":\"record\",\"name\":\"commodityClassificationAssociation\",\"name" +
				"space\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodityCode" +
				"\",\"doc\":\"A customer provided non-standardized commodity code.\",\"default\":null,\"t" +
				"ype\":[\"null\",\"string\"]},{\"name\":\"commodityName\",\"doc\":\"A customer provided non-s" +
				"tandardized commodity name.\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"c" +
				"ommodityClassification\",\"doc\":\"Standardized commodity classification information" +
				".\",\"type\":{\"type\":\"record\",\"name\":\"commodityClassification\",\"namespace\":\"com.mae" +
				"rsk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodityGroup\",\"doc\":\"The c" +
				"ommodity category type.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"" +
				"commodityGroup\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{" +
				"\"name\":\"commodityGroupCode\",\"doc\":\"The identifying code for the commodity catego" +
				"ry.\",\"type\":\"string\"},{\"name\":\"commodityGroupName\",\"doc\":\"The full name of the c" +
				"ommodity category.\",\"type\":\"string\"}]}]},{\"name\":\"commodityCode\",\"doc\":\"The HS c" +
				"ode for the commodity.\",\"type\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textua" +
				"l description of the commodity.\",\"type\":\"string\"},{\"name\":\"commodityClassificati" +
				"onChild\",\"doc\":\"A sub category commodity description. This is the top level of t" +
				"he recursion level 0 not written out here to keep the Avro schema backward and f" +
				"orward compatible.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commo" +
				"dityClassificationChild\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"f" +
				"ields\":[{\"name\":\"commodityGroup\",\"doc\":\"The commodity category type.\",\"default\":" +
				"null,\"type\":[\"null\",\"commodityGroup\"]},{\"name\":\"commodityCode\",\"doc\":\"The HS cod" +
				"e for the commodity.\",\"type\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual " +
				"description of the commodity.\",\"type\":\"string\"},{\"name\":\"commodityClassification" +
				"ChildL1\",\"doc\":\"A sub category commodity description. The lower level of the rec" +
				"ursion.\",\"default\":null,\"type\":[\"null\",{\"type\":\"record\",\"name\":\"commodityClassif" +
				"icationChildL1\",\"namespace\":\"com.maersk.orderhandling.containermain\",\"fields\":[{" +
				"\"name\":\"commodityGroup\",\"doc\":\"The commodity category type.\",\"default\":null,\"typ" +
				"e\":[\"null\",\"commodityGroup\"]},{\"name\":\"commodityCode\",\"doc\":\"The HS code for the" +
				" commodity.\",\"type\":\"string\"},{\"name\":\"commodityName\",\"doc\":\"A textual descripti" +
				"on of the commodity.\",\"type\":\"string\"},{\"name\":\"commodityCodingSystem\",\"doc\":\"Th" +
				"e system that defines the commodity codes: E.g.: Harmonized System, MARS Commodi" +
				"ty codes, ...\",\"type\":{\"type\":\"record\",\"name\":\"commodityCodingSystem\",\"namespace" +
				"\":\"com.maersk.orderhandling.containermain\",\"fields\":[{\"name\":\"commodityCodingSys" +
				"temCode\",\"doc\":\"The uniquely identifying code for the commodity coding system.\"," +
				"\"type\":\"string\"},{\"name\":\"commodityCodingSystemName\",\"doc\":\"The full name of the" +
				" commodity coding system.\",\"type\":\"string\"}]}}]}]},{\"name\":\"commodityCodingSyste" +
				"m\",\"doc\":\"The system that defines the commodity codes: E.g.: Harmonized System, " +
				"MARS Commodity codes, ...\",\"type\":\"commodityCodingSystem\"}]}]},{\"name\":\"commodit" +
				"yCodingSystem\",\"doc\":\"The system that defines the commodity codes: E.g.: Harmoni" +
				"zed System, MARS Commodity codes, ...\",\"type\":\"commodityCodingSystem\"}]}}]}}]}]}" +
				"}}]}}]}]}");
		/// <summary>
		/// A unique identifier of the equipment assignment - (INSTANCE_ID in GCSS).
		/// </summary>
		private string _shipmentEquipmentIdentifier;
		/// <summary>
		/// A description of the equipment assigned. - Only available when equipment has been matched to booking.
		/// </summary>
		private com.maersk.orderhandling.containermain.container _container;
		/// <summary>
		/// Specifies the type of reefer container to be used for the transport.
		/// </summary>
		private com.maersk.orderhandling.containermain.equipmentProfile _equipmentProfile;
		/// <summary>
		/// The style of packaging used in the container/equipment.
		/// </summary>
		private com.maersk.orderhandling.containermain.cargoPackageType _cargoPackageType;
		/// <summary>
		/// Total number of outer level packages stuffed in the container/equipment.
		/// </summary>
		private System.Nullable<System.Int32> _totalStuffedPackageQuantity;
		/// <summary>
		/// Total number of products stuffed in the container/equipment.
		/// </summary>
		private System.Nullable<System.Int32> _totalStuffedCustomerProductQuantity;
		/// <summary>
		/// The total weight of all cargo stuffed in the container/equipment including outer level packaging.
		/// </summary>
		private System.Nullable<System.Double> _totalStuffedGrossWeight;
		/// <summary>
		/// The total net weight of all cargo stuffed in the container excluding outer level packaging.
		/// </summary>
		private System.Nullable<System.Double> _totalStuffedNetWeight;
		/// <summary>
		/// The measurement unit of the total stuffed cargo weight in container/equipment.
		/// </summary>
		private com.maersk.orderhandling.containermain.totalStuffedWeightWeightUnit _totalStuffedWeightWeightUnit;
		/// <summary>
		/// The total volume of cargo stuffed in the container/equipment.
		/// </summary>
		private System.Nullable<System.Double> _totalStuffedVolume;
		/// <summary>
		/// The measurement unit of the total stuffed cargo volume in the container/equipment.
		/// </summary>
		private com.maersk.orderhandling.containermain.totalStuffedVolumeVolumeUnit _totalStuffedVolumeVolumeUnit;
		/// <summary>
		/// Indicates if equipment is owned by the customer/shipper.
		/// </summary>
		private bool _isShipperOwned;
		/// <summary>
		/// Indicates if this equipment/container has been replaced by another equipment/container of different size and/or type.
		/// </summary>
		private bool _isSubstituted;
		/// <summary>
		/// Indicates of this equipment/container has replaced another equipment/container but has different size and/or type properties than the equipment/container originally assigned to the shipment.
		/// </summary>
		private bool _isSubstitution;
		/// <summary>
		/// Indicates if this equipment/container has been replaced by another equipment/container of same size and type.
		/// </summary>
		private bool _isReplaced;
		/// <summary>
		/// Indicates of this equipment/container has replaced another equipment/container of same size and type.
		/// </summary>
		private bool _isReplacement;
		/// <summary>
		/// The equipment/container being substituted/replaced by the equipment/container that this event is about.
		/// </summary>
		private com.maersk.orderhandling.containermain.shipmentEquipmentSubstituesOrReplaces _shipmentEquipmentSubstituesOrReplaces;
		/// <summary>
		/// Description of cargo stuffing/distribution(s) in the container.
		/// </summary>
		private IList<com.maersk.orderhandling.containermain.shipmentEquipmentCargoDistribution> _shipmentEquipmentCargoDistributions;
		public virtual Schema Schema
		{
			get
			{
				return shipmentEquipment._SCHEMA;
			}
		}
		/// <summary>
		/// A unique identifier of the equipment assignment - (INSTANCE_ID in GCSS).
		/// </summary>
		public string shipmentEquipmentIdentifier
		{
			get
			{
				return this._shipmentEquipmentIdentifier;
			}
			set
			{
				this._shipmentEquipmentIdentifier = value;
			}
		}
		/// <summary>
		/// A description of the equipment assigned. - Only available when equipment has been matched to booking.
		/// </summary>
		public com.maersk.orderhandling.containermain.container container
		{
			get
			{
				return this._container;
			}
			set
			{
				this._container = value;
			}
		}
		/// <summary>
		/// Specifies the type of reefer container to be used for the transport.
		/// </summary>
		public com.maersk.orderhandling.containermain.equipmentProfile equipmentProfile
		{
			get
			{
				return this._equipmentProfile;
			}
			set
			{
				this._equipmentProfile = value;
			}
		}
		/// <summary>
		/// The style of packaging used in the container/equipment.
		/// </summary>
		public com.maersk.orderhandling.containermain.cargoPackageType cargoPackageType
		{
			get
			{
				return this._cargoPackageType;
			}
			set
			{
				this._cargoPackageType = value;
			}
		}
		/// <summary>
		/// Total number of outer level packages stuffed in the container/equipment.
		/// </summary>
		public System.Nullable<System.Int32> totalStuffedPackageQuantity
		{
			get
			{
				return this._totalStuffedPackageQuantity;
			}
			set
			{
				this._totalStuffedPackageQuantity = value;
			}
		}
		/// <summary>
		/// Total number of products stuffed in the container/equipment.
		/// </summary>
		public System.Nullable<System.Int32> totalStuffedCustomerProductQuantity
		{
			get
			{
				return this._totalStuffedCustomerProductQuantity;
			}
			set
			{
				this._totalStuffedCustomerProductQuantity = value;
			}
		}
		/// <summary>
		/// The total weight of all cargo stuffed in the container/equipment including outer level packaging.
		/// </summary>
		public System.Nullable<System.Double> totalStuffedGrossWeight
		{
			get
			{
				return this._totalStuffedGrossWeight;
			}
			set
			{
				this._totalStuffedGrossWeight = value;
			}
		}
		/// <summary>
		/// The total net weight of all cargo stuffed in the container excluding outer level packaging.
		/// </summary>
		public System.Nullable<System.Double> totalStuffedNetWeight
		{
			get
			{
				return this._totalStuffedNetWeight;
			}
			set
			{
				this._totalStuffedNetWeight = value;
			}
		}
		/// <summary>
		/// The measurement unit of the total stuffed cargo weight in container/equipment.
		/// </summary>
		public com.maersk.orderhandling.containermain.totalStuffedWeightWeightUnit totalStuffedWeightWeightUnit
		{
			get
			{
				return this._totalStuffedWeightWeightUnit;
			}
			set
			{
				this._totalStuffedWeightWeightUnit = value;
			}
		}
		/// <summary>
		/// The total volume of cargo stuffed in the container/equipment.
		/// </summary>
		public System.Nullable<System.Double> totalStuffedVolume
		{
			get
			{
				return this._totalStuffedVolume;
			}
			set
			{
				this._totalStuffedVolume = value;
			}
		}
		/// <summary>
		/// The measurement unit of the total stuffed cargo volume in the container/equipment.
		/// </summary>
		public com.maersk.orderhandling.containermain.totalStuffedVolumeVolumeUnit totalStuffedVolumeVolumeUnit
		{
			get
			{
				return this._totalStuffedVolumeVolumeUnit;
			}
			set
			{
				this._totalStuffedVolumeVolumeUnit = value;
			}
		}
		/// <summary>
		/// Indicates if equipment is owned by the customer/shipper.
		/// </summary>
		public bool isShipperOwned
		{
			get
			{
				return this._isShipperOwned;
			}
			set
			{
				this._isShipperOwned = value;
			}
		}
		/// <summary>
		/// Indicates if this equipment/container has been replaced by another equipment/container of different size and/or type.
		/// </summary>
		public bool isSubstituted
		{
			get
			{
				return this._isSubstituted;
			}
			set
			{
				this._isSubstituted = value;
			}
		}
		/// <summary>
		/// Indicates of this equipment/container has replaced another equipment/container but has different size and/or type properties than the equipment/container originally assigned to the shipment.
		/// </summary>
		public bool isSubstitution
		{
			get
			{
				return this._isSubstitution;
			}
			set
			{
				this._isSubstitution = value;
			}
		}
		/// <summary>
		/// Indicates if this equipment/container has been replaced by another equipment/container of same size and type.
		/// </summary>
		public bool isReplaced
		{
			get
			{
				return this._isReplaced;
			}
			set
			{
				this._isReplaced = value;
			}
		}
		/// <summary>
		/// Indicates of this equipment/container has replaced another equipment/container of same size and type.
		/// </summary>
		public bool isReplacement
		{
			get
			{
				return this._isReplacement;
			}
			set
			{
				this._isReplacement = value;
			}
		}
		/// <summary>
		/// The equipment/container being substituted/replaced by the equipment/container that this event is about.
		/// </summary>
		public com.maersk.orderhandling.containermain.shipmentEquipmentSubstituesOrReplaces shipmentEquipmentSubstituesOrReplaces
		{
			get
			{
				return this._shipmentEquipmentSubstituesOrReplaces;
			}
			set
			{
				this._shipmentEquipmentSubstituesOrReplaces = value;
			}
		}
		/// <summary>
		/// Description of cargo stuffing/distribution(s) in the container.
		/// </summary>
		public IList<com.maersk.orderhandling.containermain.shipmentEquipmentCargoDistribution> shipmentEquipmentCargoDistributions
		{
			get
			{
				return this._shipmentEquipmentCargoDistributions;
			}
			set
			{
				this._shipmentEquipmentCargoDistributions = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.shipmentEquipmentIdentifier;
			case 1: return this.container;
			case 2: return this.equipmentProfile;
			case 3: return this.cargoPackageType;
			case 4: return this.totalStuffedPackageQuantity;
			case 5: return this.totalStuffedCustomerProductQuantity;
			case 6: return this.totalStuffedGrossWeight;
			case 7: return this.totalStuffedNetWeight;
			case 8: return this.totalStuffedWeightWeightUnit;
			case 9: return this.totalStuffedVolume;
			case 10: return this.totalStuffedVolumeVolumeUnit;
			case 11: return this.isShipperOwned;
			case 12: return this.isSubstituted;
			case 13: return this.isSubstitution;
			case 14: return this.isReplaced;
			case 15: return this.isReplacement;
			case 16: return this.shipmentEquipmentSubstituesOrReplaces;
			case 17: return this.shipmentEquipmentCargoDistributions;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.shipmentEquipmentIdentifier = (System.String)fieldValue; break;
			case 1: this.container = (com.maersk.orderhandling.containermain.container)fieldValue; break;
			case 2: this.equipmentProfile = (com.maersk.orderhandling.containermain.equipmentProfile)fieldValue; break;
			case 3: this.cargoPackageType = (com.maersk.orderhandling.containermain.cargoPackageType)fieldValue; break;
			case 4: this.totalStuffedPackageQuantity = (System.Nullable<System.Int32>)fieldValue; break;
			case 5: this.totalStuffedCustomerProductQuantity = (System.Nullable<System.Int32>)fieldValue; break;
			case 6: this.totalStuffedGrossWeight = (System.Nullable<System.Double>)fieldValue; break;
			case 7: this.totalStuffedNetWeight = (System.Nullable<System.Double>)fieldValue; break;
			case 8: this.totalStuffedWeightWeightUnit = (com.maersk.orderhandling.containermain.totalStuffedWeightWeightUnit)fieldValue; break;
			case 9: this.totalStuffedVolume = (System.Nullable<System.Double>)fieldValue; break;
			case 10: this.totalStuffedVolumeVolumeUnit = (com.maersk.orderhandling.containermain.totalStuffedVolumeVolumeUnit)fieldValue; break;
			case 11: this.isShipperOwned = (System.Boolean)fieldValue; break;
			case 12: this.isSubstituted = (System.Boolean)fieldValue; break;
			case 13: this.isSubstitution = (System.Boolean)fieldValue; break;
			case 14: this.isReplaced = (System.Boolean)fieldValue; break;
			case 15: this.isReplacement = (System.Boolean)fieldValue; break;
			case 16: this.shipmentEquipmentSubstituesOrReplaces = (com.maersk.orderhandling.containermain.shipmentEquipmentSubstituesOrReplaces)fieldValue; break;
			case 17: this.shipmentEquipmentCargoDistributions = (IList<com.maersk.orderhandling.containermain.shipmentEquipmentCargoDistribution>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
