// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.maersk.orderhandling.containermain
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class unPackageType : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""unPackageType"",""namespace"":""com.maersk.orderhandling.containermain"",""fields"":[{""name"":""unPackageTypeCode"",""doc"":""The United Nations standardized cargo package type code."",""type"":""string""},{""name"":""unPackageTypeName"",""doc"":""The name of the United Nations standardized cargo package type."",""type"":""string""},{""name"":""unPackageTypeDescription"",""doc"":""A description of the United Nations standardized cargo package type."",""default"":null,""type"":[""null"",""string""]}]}");
		/// <summary>
		/// The United Nations standardized cargo package type code.
		/// </summary>
		private string _unPackageTypeCode;
		/// <summary>
		/// The name of the United Nations standardized cargo package type.
		/// </summary>
		private string _unPackageTypeName;
		/// <summary>
		/// A description of the United Nations standardized cargo package type.
		/// </summary>
		private string _unPackageTypeDescription;
		public virtual Schema Schema
		{
			get
			{
				return unPackageType._SCHEMA;
			}
		}
		/// <summary>
		/// The United Nations standardized cargo package type code.
		/// </summary>
		public string unPackageTypeCode
		{
			get
			{
				return this._unPackageTypeCode;
			}
			set
			{
				this._unPackageTypeCode = value;
			}
		}
		/// <summary>
		/// The name of the United Nations standardized cargo package type.
		/// </summary>
		public string unPackageTypeName
		{
			get
			{
				return this._unPackageTypeName;
			}
			set
			{
				this._unPackageTypeName = value;
			}
		}
		/// <summary>
		/// A description of the United Nations standardized cargo package type.
		/// </summary>
		public string unPackageTypeDescription
		{
			get
			{
				return this._unPackageTypeDescription;
			}
			set
			{
				this._unPackageTypeDescription = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.unPackageTypeCode;
			case 1: return this.unPackageTypeName;
			case 2: return this.unPackageTypeDescription;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.unPackageTypeCode = (System.String)fieldValue; break;
			case 1: this.unPackageTypeName = (System.String)fieldValue; break;
			case 2: this.unPackageTypeDescription = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
