apiVersion : apps/v1
kind: Deployment
metadata:
  name: aca  
  labels:
    app: aca
    product: rock
spec:
 replicas: 1
 revisionHistoryLimit: 3
 progressDeadlineSeconds: 300
 selector:
    matchLabels:
      app: aca
 template:
    metadata:
      labels:
        app: aca
        product: rock
      annotations: 
        vault.security.banzaicloud.io/vault-role:  {{aks.namespace}}
    spec:
      securityContext:
         runAsNonRoot:  true
         fsGroup: 5000      
      containers:
      - name: aca
        image: {{lib-docker-aca-image-name}}   
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 8080 
              name: api 
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
        resources:
          limits:
           cpu: 500m
           memory: 512Mi
          requests:
           cpu: 250m
           memory: 256Mi
        readinessProbe: #Failing readiness probe will stop our application from serving traffic.(for worker service not really required)
          httpGet:
            path: /health/ready
            port: 8080
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 5
        livenessProbe: #Failing liveness probe will restart the container.
          httpGet:
            path: /health/live
            port: 8080
          # length of time to wait for a pod to initialize
          # after pod startup, before applying health checking
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
        env:
        - name: ConnectionStrings__RockIntegrationConnection
          value: vault:rockddfo-kv/data/readable/{{envName}}/Geography#ConnectionStrings__RockIntegrationConnection
        - name: Serilog__WriteTo__1__Args__apiKey
          value: vault:rockddfo-kv/data/readable/{{envName}}/Geography#Serilog__WriteTo__1__Args__apiKey        
        - name: BlobConnection__AccessSettings__0__SasToken
          value: vault:rockddfo-kv/data/readable/{{envName}}/Geography#BlobConnection__AccessSettings__0__SasToken
        - name: DOTNET_ENVIRONMENT
          value: vault:rockddfo-kv/data/readable/{{envName}}/Geography#DOTNET_ENVIRONMENT
        - name: integration_api_jwtkey
          value: vault:rockddfo-kv/data/readable/{{envName}}/api#integration_api_jwtkey
