apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: integration-api
    product: rock
spec:
  type: ClusterIP
  selector:
    app: integration-api
  ports:
    - port: 5000
      targetPort: "api"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rock
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2    
spec:
  ingressClassName: nginx
  tls: 
  - hosts: 
    - {{ingressurl}}
    secretName: {{sslcertname}}
  rules:
  - host: {{ingressurl}}
    http:
      paths:
      - path: /integration-api(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 5000
