name: 'Migrate datsssabase schema'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ${{ inputs.username }}
    runs-on: ubuntu-latest
    environment : ${{ inputs.username }}
    steps:
      - name: Print the input name to STDOUT
        run: |
           echo "GITHUB_WORKSPACE = ${{ inputs.username }}"
           echo "Rahul"