# This is a basic work flow to help you get started with Actions

name: deploy

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

    secrets:
      azure_cr:
        required: true
        description: A token with access to the repository, e.g. GITHUB_TOKEN
 

jobs:
  deploy:
    name: Deploy to ${{ inputs.username }}
    runs-on: ubuntu-latest
    environment : ${{ inputs.username }}
    steps:
      - name: Print the input name to STDOUT
        run: |
           echo "Hello"
           #echo  ${{secrets.GIST_AUTH_TOKEN}}
           #echo  ${{secrets.GITHUB_TOKEN }}
           #echo  ${{ secrets.azure_cr }}
        

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      #- uses: azure/aks-set-context@v1
      #  with:
      #    creds: ${{ secrets.azure_cr }}
      #    cluster-name: rahul-cluster
      #    resource-group: CICD
