# This is a basic workflow to help you get started with Actions

name: deploy

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  deploy:
    name: Deploy to ${{ inputs.username }}
    runs-on: ubuntu-latest
    environment : ${{ inputs.username }}
    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }} 

      # Set the target Azure Kubernetes Service (AKS) cluster. 
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: rahul-cluster
          resource-group: CICD
