# This is a basic workflow to help you get started with Actions

name: HelloCI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]



  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  acr_name: rahulacrvssub.azurecr.io
  acr_user_name: rahulacrvssub
  acr_repository_name: k8sdemo
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME:   k8sdemo:${{ github.sha }}  


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: echo-default-env-variables
        run: |
           echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
           echo "github.workspace = ${{ github.workspace }}"
           echo "${{ github.workspace }}" + "\HelloWorldAPI\HelloWorldAPI.sln"
           echo "${{ github.workspace }}\HelloWorldAPI\HelloWorldAPI.sln"
           echo  ${{runner.temp}}
           echo  ${{secrets.GIST_AUTH_TOKEN}}
           echo  ${{secrets.GITHUB_TOKEN }}
           echo  ${{ github.actor }}
           echo  ${{ env.REGISTRY }}
           echo  ${{ github.repository }}
           echo  $IMAGE_NAME
           echo  $acr_name
           echo  ${{ env.acr_name }}

      - name: token-replacement
        uses: cschleiden/replace-tokens@v1.1
        with:
          tokenPrefix: '{{'
          tokenSuffix: '}}'
          files: '["**/*.json"]'
        env:
          #CDN: https://somecdn.com/...
          GIST_AUTH_TOKEN: $secrets.GIST_AUTH_TOKEN


      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      #- name: ACR
      #  uses: azure/docker-login@v1
      #  with:
      #    login-server: env.acr_name
      #    username: ${{ env.acr_user_name }}
      #    password: ${{ secrets.ACR_PWD }}
 
      #- name: ACR maersk
      #  uses: azure/docker-login@v1
      #  with:
      #    login-server: maerskao.azurecr.io
      #    username: maerskao
      #    password: odC=4ZwC9AeL=oeb=D7ujuwqwv0ICMNF
 
      #- name: Login to ACR
      #  uses: docker/login-action@v1
      #  with:
      #    registry: maerskao.azurecr.io
      #    username: maerskao
      #    password: odC=4ZwC9AeL=oeb=D7ujuwqwv0ICMNF





      #- name: Build image
      #  #run: docker build . --file ${{ github.workspace }}/HelloWorldAPI/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
      #  run: docker build . --file ${{ github.workspace }}/HelloWorldAPI/Dockerfile --tag $IMAGE_NAME --label "runnumber=${{ github.sha }}"










      #- name: Log in to registry
      #  # This is where you will update the PAT to GITHUB_TOKEN
      #  run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin





      ##- name: Push image
      ##  run: |
      ##    IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
      ##    #IMAGE_ID=ghcr.io/rk/$IMAGE_NAME


      ##    # Change all uppercase to lowercase
      ##    IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
      ##    # Strip git ref prefix from version
      ##    VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      ##    # Strip "v" prefix from tag name
      ##    [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
      ##    # Use Docker `latest` tag convention
      ##    [ "$VERSION" == "master" ] && VERSION=latest
      ##    echo IMAGE_ID=$IMAGE_ID
      ##    echo VERSION=$VERSION
      ##    docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
      ##    docker push $IMAGE_ID:$VERSION


      ###- name: Push to github registry
      ###  uses: docker/login-action@v1
      ###  with:
      ###    registry: ${{ env.REGISTRY }}
      ###    username: ${{ github.actor }}
      ###    password: ${{ secrets.GITHUB_TOKEN }}

      ###- name: Extract metadata (tags, labels) for Docker
      ###  id: meta
      ###  uses: docker/metadata-action@v1
      ###  with:
      ###    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      ###- name: Build and push Docker image
      ###  uses: docker/build-push-action@v1
      ###  with:
      ###    context: ./
      ###    file: ./Dockerfile
      ###    push: true
      ###    tags: ${{ steps.meta.outputs.tags }}
      ###    labels: ${{ steps.meta.outputs.labels }}
      
      - name: login to acr
        uses: docker/login-action@v1 
        with:
          registry: ${{ env.acr_name }}
          username: ${{ env.acr_user_name }}
          password: ${{ secrets.acr_pwd }}
          
      - run: |
          docker build -f ${{ github.workspace }}/HelloWorldAPI/Dockerfile . -t ${{ env.acr_name }}/${{ env.acr_repository_name }}:${{ github.sha }}
          docker push ${{env.acr_name}}/${{env.acr_repository_name}}:${{ github.sha }}


      - name: Push to github registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        #run: docker build . --file ${{ github.workspace }}/HelloWorldAPI/Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
        run: docker build . --file ${{ github.workspace }}/HelloWorldAPI/Dockerfile --tag $IMAGE_NAME --label "runnumber=${{ github.sha }}"

      - name: Push image
        run: |
          #IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          #IMAGE_ID=ghcr.io/rk/$IMAGE_NAME


          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION





      #- name: Restore dependencies
      #  #run: dotnet restore **/HelloWorldAPI.sln
      #  run: dotnet restore ${{ github.workspace }}/HelloWorldAPI/HelloWorldAPI.sln

      #- name: Build
      #  #run: dotnet build **/HelloWorldAPI.sln --no-restore
      #  run: dotnet build ${{ github.workspace }}/HelloWorldAPI/HelloWorldAPI.sln --no-restore

      #- name: Test
      #  #run: dotnet test **/*.UnitTests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx
      #  run: dotnet test ${{ github.workspace }}/HelloWorldAPI/HelloWorldAPI.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx













      #- name: Test
      #  run: dotnet test  -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover --no-build --verbosity normal <MyProject>.Tests/
    
      
      #- name: Copy Coverage To Predictable Location
      #  run: cp ${{ github.workspace }}/TestSample.UnitTests/TestResults/*/coverage.cobertura.xml ${{runner.temp}}/scoverage.cobertura.xml
      #  #run: cp ${{ github.workspace }}/HelloWorldAPI/HelloWorldAPI.sln ${{runner.temp}}/ 
      

      #- name: Create Test Coverage Badge
      #  uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      #  id: create_coverage_badge
      #  with:
      #    label: Unit Test Coverage
      #    color: brightgreen
      #    path: ${{runner.temp}}/scoverage.cobertura.xml
      #    gist-filename: code-coverage.json
      #    gist-id: 5bf83e97a2a65cce5fdb16e1eb1d1dbe
      #    gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       
    

      #- name: Copy Coverage To Predictable Location
      #  run: cp ${{ github.workspace }}/TestSample.UnitTests/TestResults/*/coverage.cobertura.xml ${{runner.temp}}/scoverage.cobertura.xml
      #  #run: cp ${{ github.workspace }}/HelloWorldAPI/HelloWorldAPI.sln ${{runner.temp}}/ 

 

      #- name: Code Coverage Summary Report
      #  uses: irongut/CodeCoverageSummary@v1.0.2
      #  with:
      #    filename: ${{runner.temp}}/scoverage.cobertura.xml
      #    badge: true
      #    format: 'markdown'
      #    output: 'both'
     




      #- name: Publish
      #  run: dotnet publish HelloWorldAPI/HelloWorldAPI.csproj -c Release -o web

      #- name: Upload a Build Artifact
      #  uses: actions/upload-artifact@v2.3.1
      #  with:
      #    # Artifact name
      #    name: web
      #    # A file, directory or wildcard pattern that describes what to upload
      #    path: HelloWorldAPI/web/**
      #    if-no-files-found: error 