name: 'Workflow-1'

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    name: Run Flyway migrations
    runs-on: ubuntu-20.04
    env:
      SUPABASE_HOST: db.YOUR_SUPABASE_DATABASE_HOST.supabase.co
      SUPABASE_PORT: 5432
      SUPABASE_USER: postgres
      SUPABASE_DB: postgres
    steps:
      - uses: actions/checkout@v2
      - run: >-
          #docker run --rm
          #--volume ${{ github.workspace }}/migrations:/flyway/sql:ro
          #flyway/flyway:7.12.1-alpine
          #-url="jdbc:postgresql://${{ env.SUPABASE_HOST }}:${{ env.SUPABASE_PORT }}/${{ env.SUPABASE_DB }}?sslmode=require"
          #-user="${{ env.SUPABASE_USER }}"
          #-password="${{ secrets.SUPABASE_PASS }}"
          #migrate