name: 'Workflow-1'

on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

    secrets:
      azure_cr:
        required: true
        description: A token with access to the repository, e.g. GITHUB_TOKEN 

jobs:
  deploy:
    name: Deploy to ${{ inputs.username }}
    runs-on: ubuntu-latest
    environment : ${{ inputs.username }}
    steps:
      - name: Print the input name to STDOUT
        run: |
           echo "GITHUB_WORKSPACE = ${{ inputs.username }}"
           echo "Rahul"